#!/usr/bin/env python3
"""Generate a deterministic, idempotent curriculum catalogue migration."""
from pathlib import Path
import argparse
import json
import re
import uuid

NAMESPACE = uuid.UUID("8c1b6c04-5ac5-4b36-bd1e-f2f8c2b2a0b1")


def sql(value):
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def ident(value, label):
    if not isinstance(value, str) or not re.fullmatch(r"[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*", value):
        raise ValueError(f"{label} must be a stable key: {value!r}")
    return value


def db_key(value):
    return value.lower()


def deterministic_id(kind, key):
    return str(uuid.uuid5(NAMESPACE, f"{kind}:{key}"))


def load_manifest(path):
    manifest = json.loads(Path(path).read_text(encoding="utf-8"))
    for key in ("course", "module", "activities"):
        if key not in manifest:
            raise ValueError(f"manifest missing {key}")
    course = manifest["course"]
    module = manifest["module"]
    ident(course.get("stableKey"), "course.stableKey")
    ident(module.get("stableKey"), "module.stableKey")
    if not manifest["activities"]:
        raise ValueError("manifest must contain activities")
    seen = set()
    for activity in manifest["activities"]:
        key = ident(activity.get("stableKey"), "activity.stableKey")
        if key in seen:
            raise ValueError(f"duplicate activity stable key: {key}")
        seen.add(key)
        if not activity.get("title") or not activity.get("version"):
            raise ValueError(f"activity {key} needs title and version")
        if not isinstance(activity.get("maximumScore"), (int, float)) or activity["maximumScore"] <= 0:
            raise ValueError(f"activity {key} needs a positive maximumScore")
        delivery = activity.get("delivery", {})
        if not isinstance(delivery.get("weekNumber"), int) or delivery["weekNumber"] <= 0:
            raise ValueError(f"activity {key} needs a positive delivery.weekNumber")
    return manifest


def generate(manifest):
    course = manifest["course"]
    module = manifest["module"]
    course_key = db_key(ident(course["stableKey"], "course.stableKey"))
    module_key = db_key(ident(module["stableKey"], "module.stableKey"))
    course_id = deterministic_id("course", course_key)
    module_id = deterministic_id("module", f"{course_key}:{module_key}")
    lines = [
        "-- Generated by scripts/generate-curriculum-migration.py; do not edit manually.",
        "begin;",
        "",
        "insert into learning.courses (id, stable_key, code, title, qualification_level, active)",
        f"values ({sql(course_id)}, {sql(course_key)}, {sql(course.get('code'))}, {sql(course['title'])}, {sql(course.get('qualificationLevel'))}, true)",
        "on conflict (stable_key) do update set code = excluded.code, title = excluded.title, qualification_level = excluded.qualification_level, active = true;",
        "",
        "insert into learning.modules (id, course_id, stable_key, title, sort_order, active)",
        f"values ({sql(module_id)}, (select id from learning.courses where stable_key = {sql(course_key)}), {sql(module_key)}, {sql(module['title'])}, {sql(module.get('sortOrder', 0))}, true)",
        "on conflict (course_id, stable_key) do update set title = excluded.title, sort_order = excluded.sort_order, active = true;",
        "",
    ]
    weeks = {}
    for activity in sorted(manifest["activities"], key=lambda a: (a["delivery"]["weekNumber"], a["delivery"].get("sessionNumber") or 0, a["stableKey"])):
        d = activity["delivery"]
        week_no = d["weekNumber"]
        week_key = f"week-{week_no}"
        if week_no not in weeks:
            week_id = deterministic_id("week", f"{course_key}:{module_key}:{week_key}")
            weeks[week_no] = week_id
            lines += [
                "insert into learning.curriculum_weeks (id, module_id, stable_key, title, week_number, sort_order, active)",
                f"values ({sql(week_id)}, (select id from learning.modules where course_id = (select id from learning.courses where stable_key = {sql(course_key)}) and stable_key = {sql(module_key)}), {sql(week_key)}, {sql(f'Week {week_no}')}, {week_no}, {week_no}, true)",
                "on conflict (module_id, stable_key) do update set title = excluded.title, week_number = excluded.week_number, sort_order = excluded.sort_order, active = true;",
                "",
            ]
        activity_key = db_key(activity["stableKey"])
        activity_id = deterministic_id("activity", f"{course_key}:{module_key}:{activity_key}")
        version = activity["version"]
        if re.fullmatch(r"\d+\.\d+", version):
            version = version + ".0"
        if not re.fullmatch(r"\d+\.\d+\.\d+", version):
            raise ValueError(f"activity {activity['stableKey']} has invalid version {version!r}")
        version_id = deterministic_id("version", f"{activity_key}:{version}")
        content_hash = hashlib_sha256(json.dumps(activity, sort_keys=True))
        source = activity.get("sourceFile") or f"unit3/{activity['stableKey']}"
        lines += [
            "insert into learning.activities (id, module_id, stable_key, title, activity_type, git_path, active)",
            f"values ({sql(activity_id)}, (select id from learning.modules where course_id = (select id from learning.courses where stable_key = {sql(course_key)}) and stable_key = {sql(module_key)}), {sql(activity_key)}, {sql(activity['title'])}, 'practice', {sql(source)}, true)",
            "on conflict (stable_key) do update set title = excluded.title, git_path = excluded.git_path, active = true;",
            "",
            "insert into learning.activity_versions (id, activity_id, version, content_hash, max_score, question_count, published_at)",
            f"values ({sql(version_id)}, {sql(activity_id)}, {sql(version)}, {sql(content_hash)}, {sql(activity['maximumScore'])}, {sql(sum(1 for q in activity.get('questions', []) if q.get('maxScore', 0) > 0) or activity['questionCount'] or 1)}, null)",
            "on conflict (activity_id, version) do update set max_score = excluded.max_score, question_count = excluded.question_count;",
            "",
            "insert into learning.activity_delivery (activity_version_id, academic_year_id, curriculum_week_id, week_number, session_number, sort_order, active)",
            f"select {sql(version_id)}, year.id, (select id from learning.curriculum_weeks where module_id = (select id from learning.modules where course_id = (select id from learning.courses where stable_key = {sql(course_key)}) and stable_key = {sql(module_key)}) and stable_key = {sql(f'week-{week_no}')}), {week_no}, {sql(d.get('sessionNumber'))}, {sql(activity.get('sortOrder', 0))}, true from learning.academic_years year where year.active limit 1",
            "on conflict (activity_version_id, academic_year_id, group_id) where group_id is not null do nothing;",
            "",
        ]
        for question in activity.get("questions", []):
            required = ("stableKey", "sectionKey", "sectionTitle", "questionType", "analyticsTitle", "ordinal", "maxScore")
            if any(question.get(key) in (None, "") for key in required) or question.get("maxScore", 0) <= 0:
                continue
            question_id = deterministic_id("question", f"{activity_key}:{version}:{question['stableKey']}" )
            lines += [
                "insert into learning.questions (id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score)",
                f"values ({sql(question_id)}, {sql(version_id)}, {sql(question['stableKey'])}, {sql(db_key(question['sectionKey']))}, {sql(question['sectionTitle'])}, {sql(question['questionType'])}, {sql(question['analyticsTitle'])}, {sql(question['ordinal'])}, {sql(question['maxScore'])})",
                "on conflict (activity_version_id, stable_key) do update set section_key = excluded.section_key, section_title = excluded.section_title, question_type = excluded.question_type, analytics_title = excluded.analytics_title, ordinal = excluded.ordinal, max_score = excluded.max_score;",
                "",
            ]
    lines += ["commit;", ""]
    return "\n".join(lines)


def hashlib_sha256(value):
    import hashlib
    return hashlib.sha256(value.encode()).hexdigest()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("manifest")
    parser.add_argument("output")
    args = parser.parse_args()
    manifest = load_manifest(args.manifest)
    Path(args.output).write_text(generate(manifest), encoding="utf-8")
    print(f"Generated {args.output}: {len(manifest['activities'])} activities")


if __name__ == "__main__":
    main()
