"""Week 1 teaching blocks for the T Level OS curriculum generator.

Imported by generate-os-curriculum.py. Interactive counts are per block,
not per card inside a classification or matching task.
"""

WEEK_1 = {
    "n": 1,
    "title": "Client Brief, Context and Initial Research",
    "wc": "2026-08-31",
    "phase": "analyse-problem",
    "practice": "LO1 / 1.1: interpret a client brief; research the market, problems and risks; investigate current hardware and software",
    "lo_ids": ["lo1"],
    "clientScenario": None,  # filled by the generator so the brief stays in one place
    "outcomes": [
        ("w1-interpret-brief", "Interpret a client request or project brief"),
        ("w1-research-market", "Research the market environment, common problems and risks"),
        ("w1-investigate-systems", "Investigate current hardware and software used in the context"),
    ],
    "lessons": [
        {
            "title": "Lesson 1: Annotating the client brief",
            "summary": "Use the Oakfield scenario to identify the client, users, current situation, problems, requirements and constraints.",
            "retrieval": {
                "title": "Quick check: client, users and current practice",
                "summary": "Check that you can pick out the client, the users and how Oakfield works today.",
                "type": "Diagnostic",
                "minutes": 18,
                "topics": ["Client", "Users", "Current situation"],
                "blocks": [
                    ("h2", "Quick check"),
                    ("p", "intro", "Use the Oakfield scenario at the top of this page. Work through the activities your tutor directs you to complete. Do not guess from general knowledge."),
                    ("h3", "a-retrieve", "Who and what is in the brief"),
                    ("single", "client", "Who is the client in the Oakfield scenario?",
                     [("a", "Adult learners who book a course"), ("b", "Oakfield Adult Skills Hub, the organisation requesting the system"), ("c", "Tutors who take a register"), ("d", "Microsoft, because staff already use 365")],
                     "b", "The client is the organisation that asked for the work. Oakfield Adult Skills Hub requested the service.", "Learners and tutors will use the service. They are users, not the organisation that requested it."),
                    ("single", "now", "How do learners usually request a place today?",
                     [("a", "They book online and get an instant confirmation"), ("b", "They telephone or visit reception"), ("c", "They scan a QR code in the classroom"), ("d", "They email a central bookings team with a reference number")],
                     "b", "The brief says learners usually telephone or visit reception. Analyse that current practice, not a typical commercial booking site.", "Look at what the brief says happens now."),
                    ("single", "attendance", "How do tutors record attendance during lessons today?",
                     [("a", "They mark a live dashboard on a tablet"), ("b", "They use paper registers"), ("c", "They scan learner ID badges"), ("d", "They wait for managers to complete a funding form")],
                     "b", "The brief says tutors use paper registers during lessons. That is the current attendance method.", "Do not assume a digital register already exists."),
                    ("single", "capacity", "What do managers often not know until the end of the week?",
                     [("a", "Which tutor prefers morning classes"), ("b", "Whether a course is full"), ("c", "Which programming language the new service will use"), ("d", "The name of the local authority")],
                     "b", "Managers have limited visibility of course capacity and often do not know if a course is full until information is updated at the end of the week.", "The gap is timely capacity information, not branding or technology choice."),
                    ("single", "constraint-stmt", "Which statement from the brief is a constraint?",
                     [("a", "Learners should be able to find available courses"), ("b", "Tutors should be able to record attendance"), ("c", "The project has a limited budget"), ("d", "Managers should be able to monitor attendance")],
                     "c", "A limited budget restricts what you can propose. The other options are things the service should allow people to do.", "A constraint limits the work. A requirement describes what the service should do."),
                    ("single", "problem-stmt", "Which statement describes a current problem?",
                     [("a", "Staff already use Microsoft 365"), ("b", "Personal data must follow UK GDPR"), ("c", "Staff retype paper registers into a spreadsheet after the lesson"), ("d", "The service should support screen-reader users")],
                     "c", "Retyping the same attendance facts is extra work happening now. Microsoft 365 and UK GDPR are limits. Screen-reader support is a requirement.", "A problem is harm or inefficiency happening now, not a rule or a hoped-for feature."),
                    ("h3", "b-roles", "Client, user or not involved"),
                    ("classify", "users", "Sort each group. Who would use the proposed digital service?",
                     [("user", "User of the proposed system"), ("not-user", "Not a user of the proposed system")],
                     [("item-1", "Learners looking for a course", "user"),
                      ("item-2", "Tutors recording attendance", "user"),
                      ("item-3", "Managers checking whether a course is full", "user"),
                      ("item-4", "The T Level tutor teaching this unit", "not-user"),
                      ("item-5", "Microsoft support staff", "not-user")],
                     "Learners, tutors and managers are named as people who will use the service.",
                     "The client requested the work. That does not make every nearby organisation a user."),
                    ("classify", "parties", "Is each person or group the client, a user, or neither?",
                     [("client", "Client"), ("user", "User"), ("neither", "Neither")],
                     [("item-1", "Oakfield Adult Skills Hub as the organisation requesting the work", "client"),
                      ("item-2", "An adult learner looking up an English course", "user"),
                      ("item-3", "A tutor completing a class register", "user"),
                      ("item-4", "A software vendor cold-calling Oakfield this week", "neither"),
                      ("item-5", "A manager producing a funding report", "user")],
                     "The client requested the service. Users are the people who will use it. A vendor offering a product is neither until Oakfield chooses them.",
                     "Do not treat every organisation that sells software as the client."),
                ],
            },
            "main": {
                "title": "Annotate the Oakfield brief",
                "summary": "Classify statements from the brief, match stakeholder needs, then explain constraints and gaps.",
                "type": "Guided learning",
                "minutes": 50,
                "topics": ["Client brief", "Requirements", "Constraints"],
                "blocks": [
                    ("h2", "Annotate the brief"),
                    ("p", "intro", "Keep the Oakfield scenario in view. Pull evidence from it; do not invent extra detail."),
                    ("h3", "c-kinds", "Current situation, problem, requirement or constraint"),
                    ("classify", "now-or-wrong", "Is each point how Oakfield works today, or something already going wrong?",
                     [("current", "Current situation"), ("problem", "Problem")],
                     [("item-1", "Learners telephone or visit reception to ask about courses", "current"),
                      ("item-2", "Staff retype paper information into a spreadsheet later", "problem"),
                      ("item-3", "Bookings are written in a paper diary", "current"),
                      ("item-4", "Staff at another venue cannot see the latest bookings straight away", "problem"),
                      ("item-5", "Tutors complete a paper register in the lesson", "current")],
                     "Current situation is the method in use. A problem is delay, duplication or missing information caused by that method.",
                     "Writing in a diary is current practice. Not being able to see that diary from another venue is the problem it creates."),
                    ("classify", "req-or-limit", "Is each point something the service should do, or a limit on the work?",
                     [("requirement", "Requirement"), ("constraint", "Constraint")],
                     [("item-1", "Learners should be able to find available courses", "requirement"),
                      ("item-2", "Some teaching venues have unreliable Wi-Fi", "constraint"),
                      ("item-3", "Tutors should be able to record learner attendance", "requirement"),
                      ("item-4", "Staff would prefer to avoid unnecessary new systems or training", "constraint"),
                      ("item-5", "Managers should be able to view course capacity", "requirement")],
                     "Requirements are jobs the service should support. Constraints are conditions the design must live with.",
                     "Unreliable Wi-Fi and extra training are limits. Finding courses is a required job."),
                    ("classify", "kinds", "Now classify mixed statements from the Oakfield scenario.",
                     [("current", "Current situation"), ("problem", "Problem"), ("requirement", "Requirement"), ("constraint", "Constraint")],
                     [("item-1", "Staff record bookings in a paper diary and a shared spreadsheet", "current"),
                      ("item-2", "Managers often do not know whether a course is full until the end of the week", "problem"),
                      ("item-3", "Learners should be able to request a place on a course", "requirement"),
                      ("item-4", "Personal data must be handled in accordance with UK GDPR", "constraint"),
                      ("item-5", "Tutors use paper registers during lessons", "current"),
                      ("item-6", "The project has a limited budget", "constraint")],
                     "Current practice is what happens now. A problem is what goes wrong. A requirement is what the service should do. A constraint limits how you can do it.",
                     "A constraint such as UK GDPR is not a user task. A requirement is something the service should allow someone to do."),
                    ("h3", "d-stated", "Stated, implied or not yet known"),
                    ("classify", "stated", "Is each point stated in the brief, implied by it, or not yet known?",
                     [("stated", "Stated in the brief"), ("implied", "Implied by the brief"), ("unknown", "Not yet known")],
                     [("item-1", "Learners should be able to request a place", "stated"),
                      ("item-2", "Attendance recording should still work if venue Wi-Fi drops", "implied"),
                      ("item-3", "The exact project budget", "unknown"),
                      ("item-4", "The system must follow UK GDPR", "stated"),
                      ("item-5", "How many venues Oakfield uses", "unknown")],
                     "Stated points are written in the brief. Implied points follow from what is written, such as unreliable Wi-Fi affecting a live register. Unknowns need research.",
                     "Do not treat a missing figure as if the brief had already decided it."),
                    ("classify", "implied-gap", "Does the brief force this conclusion, or would you still need to check?",
                     [("implied", "Implied by the brief"), ("unknown", "Not yet known")],
                     [("item-1", "A design that only works on fast Wi-Fi will fail in some venues", "implied"),
                      ("item-2", "Whether every classroom has a shared PC", "unknown"),
                      ("item-3", "A new system that ignores Microsoft 365 will create extra training", "implied"),
                      ("item-4", "The number of staff who can edit the shared spreadsheet", "unknown"),
                      ("item-5", "Screen-reader users must be able to complete key tasks", "implied")],
                     "If the brief already names Wi-Fi, Microsoft 365 or screen readers, the design implication follows. Staff numbers and classroom kit are not given.",
                     "Do not invent a device list. Do not ignore a named accessibility need."),
                    ("classify", "evidence-type", "Classify each analyst note.",
                     [("stated", "Stated in the brief"), ("implied", "Implied by the brief"), ("unknown", "Not yet known")],
                     [("item-1", "Oakfield wants learners to view useful course information", "stated"),
                      ("item-2", "Reception-only booking will shut out learners who cannot visit during opening hours", "implied"),
                      ("item-3", "Which Microsoft 365 apps staff already use for class lists", "unknown"),
                      ("item-4", "Personal data must be handled under UK GDPR", "stated"),
                      ("item-5", "The date the current paper diary started", "unknown")],
                     "Quote the brief for stated points. Draw a careful conclusion for implied points. Ask on site for unknowns.",
                     "Opening hours are not written down, but telephone-or-visit booking still implies a barrier for some learners."),
                    ("h3", "e-match", "Match needs, tools and constraints"),
                    ("match", "needs", "Match each need to the stakeholder it mainly serves.",
                     [("find", "Find courses and request a place"), ("register", "Record learner attendance"), ("reports", "Monitor capacity and produce funding reports")],
                     [("learner", "Learner"), ("tutor", "Tutor"), ("manager", "Manager")],
                     {"find": "learner", "register": "tutor", "reports": "manager"},
                     "The brief gives learners find-and-request, tutors attendance recording, and managers capacity and reports.",
                     "Match the need to the group who would do that job, not to whoever pays for the project."),
                    ("match", "tool-issue", "Match each current tool to the issue it creates.",
                     [("diary", "Paper diary"), ("sheet", "Shared spreadsheet"), ("reg", "Paper registers")],
                     [("issue-diary", "Staff at another venue cannot see the latest bookings"), ("issue-sheet", "Learner details may be visible to people who do not need them"), ("issue-reg", "Attendance is typed again after the lesson")],
                     {"diary": "issue-diary", "sheet": "issue-sheet", "reg": "issue-reg"},
                     "Each current tool already creates a delay, a duplication or a data-access issue.",
                     "Think about who can see the information and when it is updated."),
                    ("match", "limit-design", "Match each constraint to the design concern it raises.",
                     [("budget", "Limited budget"), ("gdpr", "UK GDPR"), ("wifi", "Unreliable venue Wi-Fi"), ("m365", "Staff already use Microsoft 365")],
                     [("concern-budget", "A large custom build may be unrealistic"), ("concern-gdpr", "Who can see learner names and how that is logged"), ("concern-wifi", "A live-only register may fail in class"), ("concern-m365", "Extra logins and training if a separate system is added")],
                     {"budget": "concern-budget", "gdpr": "concern-gdpr", "wifi": "concern-wifi", "m365": "concern-m365"},
                     "A constraint is useful when it changes a design question, not when it is copied out as a slogan.",
                     "Budget affects scale. GDPR affects access. Wi-Fi affects offline working. Microsoft 365 affects training."),
                    ("single", "wifi", "Oakfield says some venues have unreliable Wi-Fi. What should the analyst investigate next?",
                     [("a", "Which colour scheme would look modern on a booking screen"), ("b", "Whether attendance still needs to be recorded when a venue is offline, and how staff do that today"), ("c", "Which programming language is most popular this year"), ("d", "Whether the Hub should move every course to a single city-centre building")],
                     "b", "Unreliable Wi-Fi affects a live digital register. Find out what happens in class today before you recommend a design.", "A Wi-Fi problem is about how the service must work in those venues, not about branding or the tech stack."),
                    ("h3", "f-write", "Write from the brief"),
                    ("short", "client-user", "Using Oakfield, explain the difference between the client and a user.", "The client is... A user is...", "Name Oakfield as the client and give one example user from the brief.", 50),
                    ("short", "two-problems", "Identify two problems with the current process and explain why each is a problem.", "1. ... because ... 2. ... because ...", "Pick delays, missing capacity information, duplicated typing or data sitting in a shared file.", 80),
                    ("short", "implied-two", "Identify two implied requirements and explain why they are implied rather than written as a list.", "1. ... It is implied because ... 2. ...", "Start from Wi-Fi, accessibility, opening hours or Microsoft 365.", 80),
                    ("short", "constraints", "Choose one constraint from the brief and justify how it should affect the first version of the service.", "Constraint: ... It should affect the first version because...", "Use budget, UK GDPR, unreliable Wi-Fi or existing Microsoft 365. Do not just copy the constraint out.", 80),
                    ("short", "evidence", "From the brief, give one problem, one requirement, one constraint and one missing piece of information.", "Problem: ... Requirement: ... Constraint: ... Missing: ...", "Quote or closely paraphrase the scenario.", 80),
                ],
            },
            "formative": {
                "title": "Progress check: reading the brief",
                "summary": "Check that you can still tell client from user, and pick a useful follow-up question.",
                "type": "Classification",
                "minutes": 15,
                "topics": ["Client", "User", "Research questions"],
                "blocks": [
                    ("h2", "Progress check"),
                    ("classify", "sort", "Classify each statement.",
                     [("client", "Client / organisation"), ("user", "User"), ("constraint", "Constraint")],
                     [("item-1", "Oakfield Adult Skills Hub requested the digital service", "client"),
                      ("item-2", "An adult learner with a screen reader looks up a maths course", "user"),
                      ("item-3", "Some teaching venues have unreliable Wi-Fi", "constraint"),
                      ("item-4", "A tutor records who attended the session", "user"),
                      ("item-5", "Staff already use Microsoft 365", "constraint")],
                     "The client requested the work. Users are the people who will use the service. Constraints limit the design.",
                     "Paying for the work does not make Oakfield a user of every screen. Wi-Fi and Microsoft 365 are limits, not user tasks."),
                    ("short", "questions", "Write three questions an analyst should ask Oakfield before recommending a solution.", "1. ... 2. ... 3. ...", "Useful questions are specific: numbers, venues, devices, what happens if Wi-Fi fails.", 60),
                    ("short", "access-why", "Explain why accessibility matters in this Oakfield project.", "Accessibility matters because...", "Use the brief: different digital confidence, screen readers, and English as an additional language.", 80),
                    ("single", "best-question", "Which follow-up question would help most before proposing a solution?",
                     [("a", "What colour should the home page use before we know who will use it?"), ("b", "Who is allowed to edit the shared spreadsheet, and how is that access reviewed?"), ("c", "Which stock photo of a classroom should appear on a poster?"), ("d", "Should the logo include a book or a laptop?")],
                     "b", "Spreadsheet access is about personal data and current practice. It changes the design. Branding guesses do not.", "Ask about who can see learner data, not about decoration."),
                    ("short", "summarise", "In your own words, summarise Oakfield's main business problem in two or three sentences.", "Oakfield's main problem is...", "Focus on delayed information, duplicated admin and learners who cannot easily request a place. Do not paste the brief.", 80),
                ],
            },
        },
        {
            "title": "Lesson 2: Market, problems and risks",
            "summary": "Look beyond the brief: market context, problems with the current approach, and risks if nothing changes.",
            "retrieval": {
                "title": "Retrieval: market or user need?",
                "summary": "Tell a single user need apart from a wider market issue.",
                "type": "Retrieval",
                "minutes": 16,
                "topics": ["Market", "User needs"],
                "blocks": [
                    ("h2", "Market or user need?"),
                    ("p", "intro", "A user need belongs to a person using the service. A market point is about other providers, typical products or public expectation. Work through the activities your tutor directs you to complete."),
                    ("single", "q1", "Which statement is about the wider market, not one user's need?",
                     [("a", "A learner uses a screen reader to look up courses"), ("b", "Other adult-learning providers already let people request a place online"), ("c", "A tutor wants a paper backup register"), ("d", "A manager wants Friday attendance figures")],
                     "b", "The market is other providers and what is already normal around Oakfield. One person's access need is still a user need.", "A user need belongs to a person using the service."),
                    ("single", "market-expect", "Why might other providers' online requests matter to Oakfield?",
                     [("a", "Because Oakfield must copy another organisation's brand colours"), ("b", "Because learners may already expect to request a place without visiting reception"), ("c", "Because Microsoft will refuse to work with any paper process"), ("d", "Because funding reports are only accepted from mobile apps")],
                     "b", "If similar services already take online requests, Oakfield's telephone-and-visit process may feel slow or closed to some learners.", "Market research is about expectation and alternatives, not copying a logo."),
                    ("classify", "need-or-market", "Is each statement a user need or a market point?",
                     [("need", "User need"), ("market", "Market / wider context")],
                     [("item-1", "A tutor needs attendance recorded before the class leaves", "need"),
                      ("item-2", "Many adult-learning providers now publish course lists online", "market"),
                      ("item-3", "A learner with low digital confidence still needs to request a place", "need"),
                      ("item-4", "Libraries and colleges nearby already offer online enrolment", "market"),
                      ("item-5", "A manager needs reliable capacity figures in the week, not after it", "need")],
                     "User needs describe a person trying to complete a job. Market points describe what similar services already do.",
                     "Keep Oakfield's tutor, learner and manager jobs separate from what other providers offer."),
                    ("single", "problem-now", "Which point is a problem already happening, not a possible future harm?",
                     [("a", "A shared spreadsheet could be forwarded to the wrong person next term"), ("b", "Staff retype paper registers into a spreadsheet after the lesson"), ("c", "A future app store review might be poor"), ("d", "A new vendor might raise prices in three years")],
                     "b", "Retyping registers is work happening now. The other options are harms that might happen later.", "If it is already wasting time, it is a problem. If it might happen, it is a risk."),
                    ("single", "constraint-not-risk", "Which point is a constraint rather than a risk?",
                     [("a", "Learner names on a shared spreadsheet could be copied"), ("b", "Learners who will not use an app-only service may be unable to request a place"), ("c", "The project has a limited budget"), ("d", "Attendance updated too late could affect a funding report")],
                     "c", "A limited budget is a condition the work must live with. The others are harms that might follow from the current process or a poor design.", "A constraint stays true even if nobody has been harmed yet."),
                    ("classify", "sort", "Classify each Oakfield point.",
                     [("problem", "Problem"), ("risk", "Risk"), ("constraint", "Constraint")],
                     [("item-1", "Managers often do not know if a course is full until the week has ended", "problem"),
                      ("item-2", "Personal data sitting in a shared spreadsheet could be copied or sent to the wrong person", "risk"),
                      ("item-3", "The project has a limited budget", "constraint"),
                      ("item-4", "Learners queuing at reception while staff search the diary", "problem")],
                     "A problem is already happening. A risk is harm that might happen. A constraint limits what you can propose.",
                     "Budget is a limit on the work, not a user complaint happening today."),
                ],
            },
            "main": {
                "title": "Problems, risks and why they matter",
                "summary": "Connect research points back to Oakfield, not to a generic booking product.",
                "type": "Guided learning",
                "minutes": 50,
                "topics": ["Market research", "Risk", "Adult learning"],
                "blocks": [
                    ("h2", "What the current approach costs Oakfield"),
                    ("p", "intro", "A proposal that only repeats the brief is weak. Look at what similar services do, what usually goes wrong, and who gets left out."),
                    ("h3", "b-prc", "Problem, risk or constraint"),
                    ("classify", "kinds", "Classify each statement about Oakfield's current approach.",
                     [("problem", "Problem now"), ("risk", "Risk if nothing changes"), ("constraint", "Constraint")],
                     [("item-1", "Staff retype paper registers into a spreadsheet", "problem"),
                      ("item-2", "Learner data on a shared spreadsheet could be accessed by the wrong staff", "risk"),
                      ("item-3", "Some venues have unreliable Wi-Fi", "constraint"),
                      ("item-4", "Learners who will not use an app-only service may be unable to request a place", "risk"),
                      ("item-5", "Staff already use Microsoft 365 and extra systems mean extra training", "constraint")],
                     "Problems are happening now. Risks are harms that may follow. Constraints stay true even if you change the design.",
                     "Unreliable Wi-Fi limits the design. A data leak from a shared spreadsheet is a risk, not a budget limit."),
                    ("h3", "c-research", "Useful or unhelpful research"),
                    ("classify", "useful", "Which investigation would help Oakfield, and which would not?",
                     [("useful", "Useful for Oakfield"), ("not-useful", "Not useful at this stage")],
                     [("item-1", "How other adult-learning providers take bookings", "useful"),
                      ("item-2", "Whether paper registers get lost or retyped", "useful"),
                      ("item-3", "Which colour palette looks fashionable this season", "not-useful"),
                      ("item-4", "What happens to attendance data if a venue is offline", "useful"),
                      ("item-5", "Which JavaScript framework is trending this month", "not-useful")],
                     "Useful research changes what you would recommend for Oakfield's users, data or venues.",
                     "Fashion and framework trends do not close a knowledge gap in this brief."),
                    ("classify", "useful-three", "Sort each planned research activity.",
                     [("useful", "Useful for Oakfield"), ("not-useful", "Not useful at this stage")],
                     [("item-1", "Ask tutors what they do if the register is still incomplete at the end of the session", "useful"),
                      ("item-2", "Compare two nearby adult-learning course pages for what they publish before a learner telephones", "useful"),
                      ("item-3", "Design a mascot before mapping how bookings are taken", "not-useful"),
                      ("item-4", "Check whether funding reports need attendance by a set weekday", "useful"),
                      ("item-5", "Survey staff about their favourite website animation", "not-useful")],
                     "Tutors, nearby providers and reporting deadlines affect the process. Mascots and animation do not.",
                     "If the answer would not change a requirement, a risk or a constraint, skip it for now."),
                    ("h3", "d-match", "Why a finding matters"),
                    ("match", "matter-map", "Match each finding to why it matters for Oakfield.",
                     [("other", "Other adult-learning providers already take online requests"), ("sheet", "Learner names sit on a shared spreadsheet"), ("wifi", "Some venues have unreliable Wi-Fi")],
                     [("access", "Learners may expect to request a place without visiting reception"), ("gdpr", "Personal data could be copied or sent to the wrong person"), ("offline", "A live-only register may fail during a lesson")],
                     {"other": "access", "sheet": "gdpr", "wifi": "offline"},
                     "Each finding changes what you would investigate or recommend for Oakfield.",
                     "Stay with Oakfield's users, data and venues. Do not treat this as a generic booking app."),
                    ("match", "risk-impact", "Match each risk to a likely impact.",
                     [("dup", "Diary and spreadsheet disagree"), ("late", "Attendance updated at the end of the week"), ("app", "Service offered only as a smartphone app")],
                     [("impact-dup", "A learner may be told a course is free when it is full"), ("impact-late", "Managers cannot produce timely funding information"), ("impact-app", "Learners with only a library PC may be unable to request a place")],
                     {"dup": "impact-dup", "late": "impact-late", "app": "impact-app"},
                     "A risk is useful when you can name who is harmed and how.",
                     "Think about learners, managers and people with limited devices, not about a generic outage."),
                    ("match", "trend-oakfield", "Match each market observation to its relevance for Oakfield.",
                     [("online", "Course information is commonly published online before a person telephones"), ("phone", "Some public services still keep a telephone route"), ("train", "Staff training time is often underestimated in digital projects")],
                     [("rel-online", "Oakfield's reception-only route may feel slow next to nearby providers"), ("rel-phone", "Dropping the telephone route could exclude learners with low digital confidence"), ("rel-train", "A new system beside Microsoft 365 may fail if staff are not given time to learn it")],
                     {"online": "rel-online", "phone": "rel-phone", "train": "rel-train"},
                     "Market observations only help when they change an Oakfield decision.",
                     "Do not import a trend unless you can say who at Oakfield it affects."),
                    ("h3", "e-decide", "Choose the next useful step"),
                    ("single", "next-research", "Oakfield wants to know whether to keep telephone booking. What is the best next research step?",
                     [("a", "Ask a web designer for three homepage layouts"), ("b", "Find out how many enquiries come by phone, and whether those learners also have internet access"), ("c", "Buy a new phone system before collecting any figures"), ("d", "Stop answering the phone for a week to test demand")],
                     "b", "You need volume and learner access before you drop or keep a channel. Layouts and shutting the phone line do not answer that.", "Count and understand current use before changing it."),
                    ("single", "relevant-risk", "Which risk is most relevant if Oakfield puts learner names on a shared spreadsheet that many staff can open?",
                     [("a", "The spreadsheet font might look dated"), ("b", "Personal data could be seen, copied or sent to people who do not need it"), ("c", "A competitor might launch a similar spreadsheet"), ("d", "The file name might be hard to remember")],
                     "b", "Shared learner data is a UK GDPR issue. Appearance and file names are not the harm.", "Name the people and the data, not the decoration."),
                    ("single", "market-evidence", "Which piece of market evidence is useful for Oakfield?",
                     [("a", "A social network changed its logo last month"), ("b", "Two nearby adult-learning providers let people request a place without visiting reception"), ("c", "A games company released a new handheld device"), ("d", "A lifestyle magazine ranked the 'best learning apps'")],
                     "b", "Nearby providers show what learners in the same area can already do. Logos, gadgets and magazine lists do not.", "Stay in adult learning and local alternatives."),
                    ("single", "admin-cut", "Staff currently retype paper registers into a spreadsheet. Which change would most clearly reduce that work?",
                     [("a", "Printing the register on thicker paper"), ("b", "Recording attendance once, in a system tutors and managers both use"), ("c", "Asking learners to shout their names twice"), ("d", "Changing the spreadsheet font to bold")],
                     "b", "The wasted work is typing the same facts twice. One shared attendance record removes the second typing, if it still works in class.", "Look at duplicated effort, not at how the paper looks."),
                    ("h3", "f-write", "Write about problems, risks and research"),
                    ("short", "prc-diff", "Explain the difference between a problem, a risk and a constraint. Give one Oakfield example of each.", "Problem: ... Risk: ... Constraint: ...", "A problem is happening now. A risk might happen. A constraint limits the design.", 100),
                    ("short", "risk-impact-write", "Choose one Oakfield risk and explain its possible impact.", "The risk is... The impact could be...", "Say who is affected: learners, tutors, managers or funders.", 80),
                    ("short", "matter", "Choose one market finding that would be useful for Oakfield. Explain why it matters.", "Finding: ... It matters because...", "Use nearby providers, typical online requests, or whether similar services still keep a telephone route.", 80),
                    ("short", "sheet-problem", "Describe one problem caused by the shared spreadsheet process.", "The shared spreadsheet causes... because...", "Think about who can see the file, when it is updated, and whether it matches the paper diary.", 60),
                ],
            },
            "formative": {
                "title": "Progress check: problem, risk or constraint",
                "summary": "Check that you can still tell these three apart, and explain why research comes first.",
                "type": "Classification",
                "minutes": 16,
                "topics": ["Problems", "Risks", "Constraints"],
                "blocks": [
                    ("h2", "Progress check"),
                    ("classify", "sort", "Classify each statement.",
                     [("problem", "Problem"), ("risk", "Risk"), ("constraint", "Constraint")],
                     [("item-1", "Duplicate bookings because the diary and spreadsheet do not match", "problem"),
                      ("item-2", "UK GDPR rules for personal data", "constraint"),
                      ("item-3", "A missed funding report because attendance was updated too late", "risk"),
                      ("item-4", "Learners queuing at reception while staff search the diary", "problem")],
                     "If it is already going wrong, it is a problem. If it might cause harm later, it is a risk. If it limits the design, it is a constraint.",
                     "GDPR is a legal limit. Late reports are a harm that might follow from the current process."),
                    ("short", "admin-how", "Suggest one way a digital service could reduce administrative work at Oakfield, and explain how.", "A digital service could... It would reduce work by...", "Stay with bookings, registers or capacity, not with a generic app idea.", 80),
                    ("short", "research-first", "Explain why research should happen before proposing a solution.", "Research should come first because...", "Use Oakfield: Wi-Fi, Microsoft 365, who uses the spreadsheet, and who cannot visit reception.", 80),
                    ("short", "competitor", "Explain why a competitor or similar service might be worth researching.", "It is worth researching because...", "Say what you would compare: request a place, telephone option, or what is published before a visit.", 60),
                    ("short", "data-risk", "Describe one risk linked to personal data in the current process and explain why it matters.", "The risk is... It matters because...", "Evidence from the brief: names on a shared spreadsheet, UK GDPR, who can open the file.", 80),
                    ("single", "challenge-risk", "A team wants to replace telephone booking with an app in one step. What is the strongest objection from the brief?",
                     [("a", "Apps cannot list course titles"), ("b", "Some learners have lower digital confidence, and some venues have unreliable Wi-Fi"), ("c", "Managers dislike all software"), ("d", "Paper diaries are required by UK law")],
                     "b", "The brief already names digital confidence and unreliable Wi-Fi. An app-only jump could shut people out or fail on site.", "Use constraints and users already in the scenario, not invented legal rules."),
                ],
            },
        },
        {
            "title": "Lesson 3: Current systems and exit check",
            "summary": "Investigate current hardware, software and practice, then close the week with remaining unknowns.",
            "retrieval": {
                "title": "Retrieval: current tools",
                "summary": "Match what Oakfield uses now to the limitation that creates.",
                "type": "Retrieval",
                "minutes": 16,
                "topics": ["Current systems"],
                "blocks": [
                    ("h2", "What they use now"),
                    ("p", "intro", "A new service has to work with telephone, reception, paper, a shared spreadsheet, Microsoft 365 and weak Wi-Fi. Work through the activities your tutor directs you to complete."),
                    ("single", "q1", "Which current practice is already in the brief?",
                     [("a", "A dedicated student records system with live dashboards"), ("b", "Telephone and reception enquiries, a paper diary, a shared spreadsheet and paper registers"), ("c", "An app store listing for Oakfield"), ("d", "Chip-and-PIN terminals in every classroom")],
                     "b", "The brief already names telephone, reception, diary, spreadsheet and paper registers.", "Do not invent systems the brief never mentioned."),
                    ("single", "which-m365", "Why does the brief mention Microsoft 365?",
                     [("a", "Because Oakfield wants to ban all Microsoft products"), ("b", "Because staff already use it and would prefer to avoid unnecessary new systems or training"), ("c", "Because UK GDPR only applies to Microsoft files"), ("d", "Because paper registers are stored inside Outlook")],
                     "b", "Staff already use Microsoft 365. Extra systems mean extra training. That is a constraint on the proposal.", "The point is current software and training load, not a legal slogan."),
                    ("single", "phone-limit", "What limitation comes with telephone and reception enquiries?",
                     [("a", "Learners can only enquire when staff are free to answer"), ("b", "Telephone lines cannot carry a person's name"), ("c", "Reception desks are illegal under UK GDPR"), ("d", "Tutors must answer every call during a lesson")],
                     "a", "If staff are busy or the venue is closed, a learner cannot request a place. That is the limitation of the current channel.", "The brief does not ban reception. It does make access depend on staff being free."),
                    ("single", "wifi-now", "Which current environment fact should shape a live digital register?",
                     [("a", "Every Oakfield venue has guaranteed fibre broadband"), ("b", "Some teaching venues have unreliable Wi-Fi"), ("c", "Tutors are forbidden from using paper"), ("d", "Registers are already taken automatically by cameras")],
                     "b", "Unreliable Wi-Fi is already in the brief. A design that only works while online may fail in class.", "Do not assume perfect connectivity or cameras."),
                    ("match", "tools", "Match the current tool to a limitation.",
                     [("phone", "Telephone and reception"), ("diary", "Paper diary"), ("sheet", "Shared spreadsheet")],
                     [("lim-phone", "Learners can only enquire when staff are free to answer"), ("lim-diary", "Staff at another venue cannot see the latest bookings"), ("lim-sheet", "The wrong person may be able to open learner data")],
                     {"phone": "lim-phone", "diary": "lim-diary", "sheet": "lim-sheet"},
                     "Each current tool already creates a problem the new service has to deal with.",
                     "Think about who can see the information and when a learner can get an answer."),
                    ("match", "tools-more", "Match these further tools to a limitation.",
                     [("reg", "Paper registers"), ("office", "Microsoft 365"), ("wifi", "Venue Wi-Fi")],
                     [("lim-reg", "Attendance is typed again after the lesson"), ("lim-office", "Extra systems would mean extra training"), ("lim-wifi", "A cloud-only register may fail during the session")],
                     {"reg": "lim-reg", "office": "lim-office", "wifi": "lim-wifi"},
                     "Registers, existing software and connectivity all constrain a realistic design.",
                     "Think about duplicated typing, training load and what happens if a venue is offline."),
                ],
            },
            "main": {
                "title": "Investigate current systems",
                "summary": "Separate what the brief already tells you from what you still need to check on site.",
                "type": "Guided learning",
                "minutes": 50,
                "topics": ["Hardware", "Software", "Practice"],
                "blocks": [
                    ("h2", "Known facts and research gaps"),
                    ("p", "intro", "Microsoft 365, paper and weak Wi-Fi all shape a realistic proposal. Write down what you still need to see on site."),
                    ("h3", "b-match", "From limitation to design question"),
                    ("match", "tools-four", "Match each environment fact to a design question.",
                     [("m365", "Staff already use Microsoft 365"), ("wifi2", "Some venues have unreliable Wi-Fi"), ("gdpr2", "Personal data must follow UK GDPR")],
                     [("q-m365", "Can the new service use existing logins instead of a separate account?"), ("q-wifi2", "How will tutors record attendance if the connection drops?"), ("q-gdpr2", "Who is allowed to see learner names, and is that access logged?")],
                     {"m365": "q-m365", "wifi2": "q-wifi2", "gdpr2": "q-gdpr2"},
                     "A current-system fact should turn into a question you can take to Oakfield.",
                     "Do not stop at copying the constraint. Ask how it would work on a Tuesday evening class."),
                    ("h3", "c-known", "Known information or research gap"),
                    ("classify", "gaps", "Is this already known from the brief, or still a research gap?",
                     [("known", "Known from the brief"), ("gap", "Still a research gap")],
                     [("item-1", "Staff already use Microsoft 365", "known"),
                      ("item-2", "Some venues have unreliable Wi-Fi", "known"),
                      ("item-3", "Exactly how many venues there are", "gap"),
                      ("item-4", "Bookings are recorded in a paper diary and a shared spreadsheet", "known"),
                      ("item-5", "Whether every classroom has a shared PC", "gap")],
                     "Known facts come from the brief. Gaps need a site visit, interview or sample of current files.",
                     "Microsoft 365 and Wi-Fi problems are already stated. Exact venue count is not."),
                    ("classify", "gaps-more", "Known from the brief, or still to check?",
                     [("known", "Known from the brief"), ("gap", "Still a research gap")],
                     [("item-1", "Tutors use paper registers during lessons", "known"),
                      ("item-2", "Who currently has permission to edit the shared spreadsheet", "gap"),
                      ("item-3", "Learners usually telephone or visit reception", "known"),
                      ("item-4", "Whether tutors have a work laptop in every venue", "gap"),
                      ("item-5", "The project has a limited budget", "known")],
                     "Channels, paper registers and budget are stated. Permissions and device lists are not.",
                     "If you cannot point to a sentence in the brief, treat it as a gap."),
                    ("h3", "d-ask", "Useful investigation questions"),
                    ("classify", "ask", "Which questions would help an analyst investigate the current system?",
                     [("useful", "Useful question"), ("not-useful", "Not useful yet")],
                     [("item-1", "Who is allowed to edit the shared spreadsheet?", "useful"),
                      ("item-2", "What happens to a booking if two people telephone at once?", "useful"),
                      ("item-3", "Which stock photo of a handshake should appear on the home page?", "not-useful"),
                      ("item-4", "Can tutors take a register when the venue Wi-Fi is down?", "useful"),
                      ("item-5", "Which colour should the logo use before the process is mapped?", "not-useful")],
                     "Useful questions uncover access, double-booking, offline working or how Microsoft 365 is used now.",
                     "Branding guesses do not explain how the current system works."),
                    ("classify", "ask-more", "Would this question help on a site visit?",
                     [("useful", "Useful question"), ("not-useful", "Not useful yet")],
                     [("item-1", "Which Microsoft 365 apps do staff already open for class lists?", "useful"),
                      ("item-2", "Is there a printer or shared PC in the classroom?", "useful"),
                      ("item-3", "Should the loading animation bounce or fade?", "not-useful"),
                      ("item-4", "How is a cancelled place removed from the diary and the spreadsheet?", "useful"),
                      ("item-5", "What is the project team's favourite website animation?", "not-useful")],
                     "Apps in use, classroom kit and cancellation steps change the design. Animation and films do not.",
                     "Ask about the job staff already do, not about decoration."),
                    ("classify", "ask-three", "Sort each planned question.",
                     [("useful", "Useful question"), ("not-useful", "Not useful yet")],
                     [("item-1", "How long does it take to type a register into the spreadsheet after class?", "useful"),
                      ("item-2", "Are there learners who only ever enquire by telephone?", "useful"),
                      ("item-3", "Should error messages use a serif font?", "not-useful"),
                      ("item-4", "Where is the paper diary stored overnight?", "useful"),
                      ("item-5", "Which stock photo of a classroom looks friendliest?", "not-useful")],
                     "Time, telephone-only learners and where the diary lives are current-system facts. Fonts and stock photos are not.",
                     "If the answer would not change hardware, software or practice, leave it."),
                    ("h3", "e-decide", "Choose a sensible next step"),
                    ("single", "next-site", "You can visit one Oakfield venue this week. What should you observe first?",
                     [("a", "The colour of the corridor display boards"), ("b", "How a booking is taken, where it is written, and who can see that record afterwards"), ("c", "Whether the staff-room kettle is new"), ("d", "How the reception plants are arranged")],
                     "b", "You are investigating the current information process: capture, storage and access. Displays and plants do not explain that.", "Watch the job, not the furniture."),
                    ("single", "replace-all", "A teammate says Oakfield should throw away Microsoft 365, paper and the phone line in month one. What is the strongest reason to slow down?",
                     [("a", "Paper can never store a person's name"), ("b", "Staff already use Microsoft 365, some learners use the telephone, and some venues have weak Wi-Fi"), ("c", "UK GDPR bans all digital systems"), ("d", "Tutors refuse to record attendance in any form")],
                     "b", "The brief already shows existing software, an analogue channel and weak connectivity. Replacing everything at once ignores those facts.", "The brief does not ban digital systems or attendance recording."),
                    ("single", "compat-next", "Which compatibility question should be investigated before buying a separate booking product?",
                     [("a", "Can staff sign in with the Microsoft 365 account they already use?"), ("b", "Does the product include a mascot builder?"), ("c", "Does the vendor brochure mention 'innovation'?"), ("d", "Does the demo video include background music?")],
                     "a", "Staff already use Microsoft 365. A second login and a second place to look up a class list is extra training and extra risk.", "Compatibility here means existing accounts and files, not marketing extras."),
                    ("h3", "f-write", "Explain how current systems shape a proposal"),
                    ("short", "compat", "Why does it matter that staff already use Microsoft 365?", "It matters because...", "Think about training, login and whether a new system would sit beside what they already open every day.", 80),
                    ("short", "compat-q", "Describe one compatibility question that should be investigated at Oakfield.", "One question is...", "You might ask about logins, class lists, or whether a new tool can export to the spreadsheet they already use.", 60),
                    ("short", "wifi-design", "Explain how weak connectivity could affect system design.", "Weak connectivity could affect the design because...", "Talk about registers in class, not about home broadband in general.", 80),
                    ("short", "compare-manual", "Compare one manual Oakfield process with a possible digital alternative. What would improve, and what could get worse?", "Manual process: ... Digital alternative: ... Improve: ... Worse: ...", "Use bookings, registers or capacity. Mention Wi-Fi or training if relevant.", 100),
                    ("short", "cost-hw", "Explain how current hardware or software could affect cost.", "Cost could change because...", "Think about extra licences, extra devices, or retraining if staff already have Microsoft 365.", 80),
                ],
            },
            "formative": {
                "title": "Exit check: remaining unknowns",
                "summary": "Leave with one unknown that still needs investigation, and a justified next step.",
                "type": "Exit ticket",
                "minutes": 16,
                "topics": ["Unknowns", "Current systems"],
                "blocks": [
                    ("h2", "Exit ticket"),
                    ("short", "unknown", "Name one thing about Oakfield's current hardware, software or practice that the brief does not tell you. Why would you need it before proposing a solution?", "Unknown: ... Why I need it: ...", "Keep it specific: a venue, a file, a permission or a device.", 80),
                    ("short", "next-area", "Recommend one area Oakfield should investigate next and justify your choice.", "Investigate... because...", "Pick spreadsheet permissions, offline registers, venue kit, or telephone-only learners.", 80),
                    ("short", "replace-write", "Recommend one current Oakfield tool or channel that should stay in increment 1, and justify your choice.", "Keep: ... because...", "You might keep the telephone route, Microsoft 365, or a paper backup register. Use the brief.", 80),
                    ("classify", "last-sort", "Is each item known, a gap, or a poor next step?",
                     [("known", "Known from the brief"), ("gap", "Research gap"), ("poor", "Poor next step")],
                     [("item-1", "Tutors use paper registers", "known"),
                      ("item-2", "Whether a classroom PC is available in every venue", "gap"),
                      ("item-3", "Choosing homepage colours before mapping the current process", "poor"),
                      ("item-4", "Some venues have unreliable Wi-Fi", "known"),
                      ("item-5", "Who can edit the shared spreadsheet", "gap")],
                     "Paper registers and Wi-Fi are stated. Device lists and permissions are gaps. Homepage colours do not explain the current system.",
                     "Do not spend the next visit on decoration."),
                    ("single", "challenge-unknown", "Which remaining unknown would most affect whether a live digital register is realistic?",
                     [("a", "The snacks available in the staff room"), ("b", "What tutors currently do if they cannot get a connection during the lesson"), ("c", "Whether the reception desk is oak or pine"), ("d", "The year the building was painted")],
                     "b", "If tutors already have an offline method, a live-only product may be rejected. Furniture and paint do not answer that.", "Ask about the workaround that already exists."),
                ],
            },
        },
    ],
    "homework": {
        "title": "Homework: one real digital product",
        "summary": "Analyse one real digital product or service using the same headings you used on the Oakfield brief.",
        "id_suffix": "product",
        "minutes": 25,
        "topics": ["Client", "Users", "Problem"],
        "blocks": [
            ("h2", "Independent study"),
            ("p", "intro", "Choose one real public or education service, such as booking, benefits, learning or libraries. Do not invent a fictional start-up. Short notes are enough."),
            ("short", "name", "Product or service name", "Name: ...", 8),
            ("short", "problem", "What problem does it address?", "Problem: ...", 30),
            ("short", "client", "Who is the likely client?", "Client: ...", 15),
            ("short", "users", "Who are the likely users?", "Users: ...", 15),
            ("short", "feature", "Name one useful feature.", "Feature: ...", 20),
            ("short", "limit", "Name one limitation or risk.", "Limitation or risk: ...", 30),
            ("short", "source", "What source did you use?", "Source: ...", "A public website, help page or app listing is enough.", 15),
        ],
    },
}
