"""Week 2 teaching blocks for the T Level OS curriculum generator.

Imported by generate-os-curriculum.py.

Week 2 taught lessons use one top-level activity per exercise. Count
activities, not items on a classification or drag-drop board.

LO1 / 1.1 — research emerging technologies; evaluate existing and potential
solutions; identify regulations and personal knowledge gaps.
"""


def E(n, title, summary, kind, minutes, topics, *blocks):
    return {
        "id": f"ex-{n:02d}",
        "title": title,
        "summary": summary,
        "type": kind,
        "minutes": minutes,
        "topics": list(topics),
        "blocks": list(blocks),
    }


SC = "Single choice"
CL = "Classification"
MA = "Matching"
WR = "Written response"

WEEK_2 = {
    "n": 2,
    "title": "Emerging Technologies, Solutions and Knowledge Gaps",
    "wc": "2026-09-07",
    "phase": "analyse-problem",
    "practice": "LO1 / 1.1 — research emerging technologies; evaluate existing and potential solutions; identify regulations and personal knowledge gaps",
    "lo_ids": ["lo1"],
    "outcomes": [
        ("w2-research-emerging", "Research newly emerging technologies"),
        ("w2-evaluate-solutions", "Evaluate existing and potential solutions against user needs"),
        ("w2-identify-gaps", "Identify guidelines, regulations and personal knowledge gaps"),
    ],
    "lessons": [
        {
            "title": "Lesson 1: Existing versus emerging options",
            "summary": "Retrieve Week 1 findings, then research and compare emerging technologies against established approaches for Oakfield.",
            "exercises": [
                E(1, "What do staff use today?", "Retrieve the current booking and attendance methods.", SC, 2, ["Current systems"],
                  ("single", "now", "What do Oakfield staff use today to take bookings and registers?",
                   [("a", "A live cloud MIS with biometric attendance in every venue"), ("b", "A paper diary and shared spreadsheet for bookings, and paper registers in class"), ("c", "Only a smartphone app that learners must install"), ("d", "An AI recommender that books places automatically")],
                   "b", "Week 1 established paper diary, shared spreadsheet and paper registers. Do not invent a live MIS the brief never described.", "Retrieve the current systems before talking about newer options.")),
                E(2, "When is a technology 'emerging'?", "Emerging is about adoption in context, not a marketing label.", SC, 2, ["Emerging technology"],
                  ("single", "q1", "A technology is 'emerging' in this Oakfield project when:",
                   [("a", "It is digital"), ("b", "It is still developing or not yet a normal fit for this adult-learning context"), ("c", "A vendor advertised it this week"), ("d", "It uses the cloud")],
                   "b", "Emerging is about development and adoption in context, not a marketing label.", "Something can be current in one sector and emerging in adult-learning admin.")),
                E(3, "Established in this context", "Name what is already normal for Oakfield staff.", SC, 2, ["Emerging technology"],
                  ("single", "estab", "Which option is already established for Oakfield staff, based on the brief?",
                   [("a", "Biometric attendance for every adult learner"), ("b", "Microsoft 365 email and files already used by staff"), ("c", "AI course matching for low-confidence learners"), ("d", "QR-only booking with no telephone route")],
                   "b", "Staff already use Microsoft 365. Biometrics and AI matching are not normal practice in this brief.", "Established means already in use here, not trending elsewhere.")),
                E(4, "Why research before proposing?", "Research should change what you would recommend.", SC, 2, ["Research"],
                  ("single", "why-research", "Why should Oakfield research emerging options before writing a proposal?",
                   [("a", "So the team can paste a vendor slogan into the report"), ("b", "So benefits, limits, maturity and fit to users can be judged with evidence"), ("c", "Because every new tool is automatically better than paper"), ("d", "Because UK GDPR bans all research")],
                   "b", "Research is how you gather evidence about fitness, risk and readiness — not how you collect slogans.", "An emerging tool is not automatically better.")),
                E(5, "Emerging or established for Oakfield", "Judge the adult-learning admin context, not tech news.", CL, 3, ["Emerging technology"],
                  ("classify", "sort-tech", "Classify each technology for Oakfield's adult-learning admin.",
                   [("emerging", "Emerging in this context"), ("established", "Established in this context")],
                   [("item-1", "Paper diary and shared spreadsheet for bookings", "established"),
                    ("item-2", "Biometric attendance for adult learners", "emerging"),
                    ("item-3", "Microsoft 365 email already used by staff", "established"),
                    ("item-4", "AI course matching for learners with low digital confidence", "emerging"),
                    ("item-5", "Telephone and reception enquiries", "established")],
                   "Established means already normal for Oakfield. Emerging means still unusual or developing in this setting.",
                   "Do not classify from a general tech blog; use Oakfield's context.")),
                E(6, "Source quality for technology research", "Separate usable evidence from marketing noise.", CL, 3, ["Sources"],
                  ("classify", "sources", "Classify each source for researching an emerging attendance tool.",
                   [("usable", "Usable evidence"), ("weak", "Weak / marketing-heavy")],
                   [("item-1", "ICO guidance on biometric data", "usable"),
                    ("item-2", "A vendor homepage that only says 'AI-powered transformation'", "weak"),
                    ("item-3", "A case study from a similar adult-learning provider with dates and outcomes", "usable"),
                    ("item-4", "An anonymous social post claiming 'everyone uses biometrics now'", "weak"),
                    ("item-5", "Centre acceptable-use policy for AI tools", "usable")],
                   "Usable sources name context, dates, risks or rules. Marketing slogans and anonymous posts do not.",
                   "Prefer regulators, similar providers and centre policy over hype.")),
                E(7, "Benefit or limitation", "Separate upside from downside for Oakfield users.", CL, 3, ["Evaluation"],
                  ("classify", "benefit-limit", "Is each point mainly a benefit or a limitation for Oakfield?",
                   [("benefit", "Benefit"), ("limitation", "Limitation")],
                   [("item-1", "Learners could request a place without visiting reception", "benefit"),
                    ("item-2", "An app-only tool may exclude people who only use a library PC", "limitation"),
                    ("item-3", "Managers could see capacity earlier in the week", "benefit"),
                    ("item-4", "Biometrics may need extra lawful-basis advice under UK GDPR", "limitation"),
                    ("item-5", "Staff already know Microsoft 365, so a Power Apps route may need less new training", "benefit")],
                   "Benefits help named users. Limitations raise exclusion, legal, training or connectivity issues.",
                   "Stay with Oakfield's learners, tutors and managers.")),
                E(8, "Ready enough or too early?", "Maturity is about fit and readiness, not novelty.", CL, 3, ["Maturity"],
                  ("classify", "maturity", "For a first Oakfield increment, how ready is each idea?",
                   [("ready", "Worth evaluating seriously now"), ("early", "Too early / high uncertainty for increment 1")],
                   [("item-1", "Improving the shared spreadsheet process with clearer permissions", "ready"),
                    ("item-2", "Fully autonomous AI that books places without staff review", "early"),
                    ("item-3", "Microsoft Forms or Power Apps on existing 365", "ready"),
                    ("item-4", "Experimental biometric gates in every community venue this term", "early"),
                    ("item-5", "Keeping a telephone route while adding an online request form", "ready")],
                   "Ready options can be evaluated against users, cost and GDPR now. Speculative full automation is too early for increment 1.",
                   "Maturity includes training, connectivity and legal readiness, not just demos.")),
                E(9, "Match technologies to research questions", "Each option should produce a concrete question.", MA, 3, ["Research"],
                  ("match", "tech-ask", "Match each candidate technology to a useful research question.",
                   [("bio", "Biometric attendance"), ("ai", "AI course matching"), ("forms", "Microsoft Forms on existing 365")],
                   [("q-bio", "What lawful basis and special-category conditions would apply?"), ("q-ai", "How would low digital-confidence learners get a clear human alternative?"), ("q-forms", "Can staff use existing Microsoft accounts without a second login?")],
                   {"bio": "q-bio", "ai": "q-ai", "forms": "q-forms"},
                   "Research questions should expose legal, inclusion or training issues before anyone buys a tool.",
                   "Do not stop at 'is it modern?'.")),
                E(10, "Match source types to purpose", "Different sources answer different questions.", MA, 3, ["Sources"],
                  ("match", "source-purpose", "Match each source type to what it is best for.",
                   [("ico", "ICO / data-protection guidance"), ("case", "Similar adult-learning case study"), ("vendor", "Vendor product brochure")],
                   [("p-ico", "Legal and privacy constraints"), ("p-case", "How a comparable organisation used the approach"), ("p-vendor", "Claimed features — treat critically")],
                   {"ico": "p-ico", "case": "p-case", "vendor": "p-vendor"},
                   "Guidance, peer practice and vendor claims are not interchangeable.",
                   "Vendor material can list features; it rarely proves fit for Oakfield.")),
                E(11, "Match criteria to why they matter", "Criteria must change a recommendation.", MA, 3, ["Evaluation"],
                  ("match", "criteria-why", "Match each comparison criterion to why it matters for Oakfield.",
                   [("cost", "Cost including training"), ("exclude", "Digital exclusion risk"), ("lock", "Vendor lock-in")],
                   [("w-cost", "Limited budget and staff time already constrain the project"), ("w-exclude", "Some learners have lower digital confidence or no smartphone"), ("w-lock", "Oakfield may struggle later if data and processes are trapped with one supplier")],
                   {"cost": "w-cost", "exclude": "w-exclude", "lock": "w-lock"},
                   "Each criterion links to a fact already in the Oakfield brief or a realistic follow-on risk.",
                   "Do not invent criteria that never affect a decision.")),
                E(12, "Match maturity signals", "Drag each signal to what it suggests.", MA, 3, ["Maturity"],
                  ("match", "maturity-signal", "Match each signal to what it suggests about readiness.",
                   [("pilot", "A short pilot in one venue with clear success measures"), ("hype", "Only social-media claims with no comparable organisation"), ("policy", "Centre AI policy and DPO advice already obtained")],
                   [("s-pilot", "Can be evaluated carefully with limited risk"), ("s-hype", "Evidence is too weak to recommend yet"), ("s-policy", "Governance readiness is improving")],
                   {"pilot": "s-pilot", "hype": "s-hype", "policy": "s-policy"},
                   "Maturity is shown by pilots, governance and comparable practice — not by slogans.",
                   "A pilot with measures is stronger than viral claims.")),
                E(13, "Weakest evaluation", "Personal taste is not a criterion.", SC, 2, ["Evaluation"],
                  ("single", "weak-eval", "Which statement is weakest as an evaluation of an emerging tool for Oakfield?",
                   [("a", "Cost including staff training"), ("b", "Whether learners with low digital confidence can complete a booking"), ("c", "Whether the tutor personally enjoys using AI chat"), ("d", "Whether personal data stays under UK GDPR controls")],
                   "c", "Personal taste is not an evaluation criterion for a public adult-learning service.", "Use purpose, users, cost, risk and regulation.")),
                E(14, "Best next research step", "Close a named uncertainty.", SC, 2, ["Research"],
                  ("single", "next-step", "A teammate likes biometric attendance. What is the best next research step?",
                   [("a", "Order hardware for every venue this week"), ("b", "Check ICO / DPO guidance and whether any similar provider has published outcomes"), ("c", "Assume it is fine because a shop uses fingerprints"), ("d", "Drop telephone booking immediately")],
                   "b", "Legal and comparable-practice questions come before buying hardware.", "Close the knowledge gap with reliable sources first.")),
                E(15, "Relevance to organisational needs", "Link technology to Oakfield's stated jobs.", SC, 2, ["Organisational needs"],
                  ("single", "relevance", "Which emerging idea is most clearly linked to a stated Oakfield need?",
                   [("a", "A classroom lighting system that changes colour for 'wellbeing'"), ("b", "An online request form so learners can ask for a place without only using reception"), ("c", "A public leaderboard of learner scores"), ("d", "A mascot generator for the logo")],
                   "b", "Learners should be able to request a place. That need is in the brief. Lighting and mascots are not.", "Relevance means the technology helps a stated job for learners, tutors or managers.")),
                E(16, "Hype versus evidence", "Reject empty modernity claims.", SC, 2, ["Sources"],
                  ("single", "hype", "Which justification relies on hype rather than evidence?",
                   [("a", "A similar college published a dated review of online requests and exclusion risks"), ("b", "AI matching sounds modern so Oakfield should use it"), ("c", "UK GDPR guidance raises special-category issues for some biometrics"), ("d", "Venue Wi-Fi is unreliable, so a live-only product needs an offline plan")],
                   "b", "'Sounds modern' is preference and hype, not evaluation.", "Evidence names sources, users or constraints.")),
                E(17, "Define emerging for Oakfield", "Use context, not a dictionary slogan only.", WR, 4, ["Emerging technology"],
                  ("short", "define", "In your own words, explain what 'emerging technology' means for this Oakfield project.", "Emerging here means...", "Mention development or adoption in adult-learning admin, not only that something is digital.", 60)),
                E(18, "One emerging option with a source", "Name benefit, risk and source.", WR, 4, ["Research"],
                  ("short", "one-tech", "Name one emerging technology relevant to Oakfield. Give one benefit, one risk and one source type you would use.", "Technology: ... Benefit: ... Risk: ... Source type: ...", "Examples: AI matching, biometrics, QR attendance. Source types: ICO, similar provider, centre policy.", 80)),
                E(19, "Why a source is usable", "Explain fitness for a proposal.", WR, 4, ["Sources"],
                  ("short", "source-why", "You find a 2024 case study from a UK adult-learning provider about online course requests. Why is that more usable than a vendor slogan page?", "It is more usable because...", "Talk about context, dated outcomes and comparable users — not about design polish.", 70)),
                E(20, "Compare existing and emerging", "Use at least three criteria.", WR, 4, ["Evaluation"],
                  ("short", "compare", "Compare paper-plus-spreadsheet with one emerging alternative. Use at least three criteria.", "Existing: ... Emerging: ... Criteria: ...", "Use purpose/users, cost/training, risk, regulation or exclusion.", 100)),
                E(21, "Justify emerging vs established", "Stay in adult-learning admin.", WR, 4, ["Emerging technology"],
                  ("short", "justify", "Pick one technology. Explain why it is emerging rather than established for Oakfield.", "Technology: ... It is emerging here because...", "Do not only say it is new. Say why Oakfield does not already treat it as normal practice.", 70)),
                E(22, "Maturity and increment 1", "Recommend caution or careful evaluation.", WR, 4, ["Maturity"],
                  ("short", "maturity-write", "Would you put fully automatic AI booking into Oakfield's first increment? Justify using maturity and user risk.", "Recommendation: ... Because...", "Mention staff review, digital confidence, and what is still unknown.", 80)),
                E(23, "Evidence or preference", "Spot evaluations that use taste instead of criteria.", CL, 3, ["Evaluation"],
                  ("classify", "evidence-pref", "Classify each justification.",
                   [("evidence", "Uses evidence / criteria"), ("preference", "Personal preference or hype")],
                   [("item-1", "Biometric registers may need extra lawful-basis advice under UK GDPR", "evidence"),
                    ("item-2", "AI matching sounds modern so we should use it", "preference"),
                    ("item-3", "An app-only service would exclude learners who only use the library PC", "evidence"),
                    ("item-4", "I like the vendor's logo", "preference"),
                    ("item-5", "Staff already use Microsoft 365, so extra logins add training cost", "evidence")],
                   "Evidence links to users, law, cost or constraints. Preference and hype do not.",
                   "Taste is not an evaluation criterion.")),
                E(24, "Match risks to emerging options", "Name who could be harmed.", MA, 3, ["Risk"],
                  ("match", "risk-map", "Match each emerging option to a realistic Oakfield risk.",
                   [("opt-bio", "Biometric attendance"), ("opt-app", "App-only course requests"), ("opt-ai", "AI matching without a human path")],
                   [("r-bio", "Special-category data handling may be unclear"), ("r-app", "Learners without smartphones may be shut out"), ("r-ai", "Unclear or biased recommendations without staff review")],
                   {"opt-bio": "r-bio", "opt-app": "r-app", "opt-ai": "r-ai"},
                   "A useful risk names people and data, not a vague fear of 'change'.",
                   "Stay with Oakfield's learners and legal duties.")),
                E(25, "Organisational relevance check", "Reject tech that does not serve stated jobs.", SC, 2, ["Organisational needs"],
                  ("single", "org-check", "A vendor offers Oakfield an 'innovative AR campus tour'. What is the strongest reason to deprioritise it for this project?",
                   [("a", "AR is never used in education"), ("b", "It does not clearly help bookings, registers or capacity — the jobs in the brief"), ("c", "AR cannot display text"), ("d", "Managers dislike all new ideas")],
                   "b", "Relevance is judged against stated organisational needs, not against novelty.", "Tour demos do not fix delayed capacity or duplicated admin.")),
                E(26, "Research log entry", "Practise recording unknowns honestly.", WR, 4, ["Research"],
                  ("short", "log", "Write one research-log entry: technology, one unknown, and the next action to close it.", "Technology: ... Unknown: ... Next action: ...", "Actions might be: check ICO page, ask DPO, interview a tutor, review a similar provider.", 70)),
                E(27, "Compare two emerging options", "Do not pick a winner without criteria.", WR, 4, ["Comparison"],
                  ("short", "two-emerging", "Briefly compare two emerging options for Oakfield on users, risk and readiness. Do not declare a final purchase.", "Option A: ... Option B: ... Users: ... Risk: ... Readiness: ...", "Keep both options honest about unknowns.", 100)),
                E(28, "Recommend a research priority", "Justify what to investigate first.", WR, 4, ["Research"],
                  ("short", "priority", "Recommend one emerging technology Oakfield should research first this week, and justify the priority.", "Research first: ... Because...", "Link to a stated need (request a place, attendance, capacity) and to risk or readiness.", 80)),
            ],
        },
        {
            "title": "Lesson 2: Evaluate candidate solutions",
            "summary": "Evaluate existing and potential solutions against different Oakfield user needs, including conflicting priorities.",
            "exercises": [
                E(1, "Retrieve comparison criteria", "List criteria before choosing a favourite.", SC, 2, ["Evaluation criteria"],
                  ("single", "criteria-q", "Which option is weakest as an evaluation criterion for Oakfield solutions?",
                   [("a", "Cost including staff training"), ("b", "Whether learners with low digital confidence can complete a booking"), ("c", "Whether the tutor personally enjoys using AI chat"), ("d", "Whether personal data stays under UK GDPR controls")],
                   "c", "Personal taste is not an evaluation criterion for a public service.", "Use purpose, users, cost, risk and regulation.")),
                E(2, "Client need versus end-user need", "The client requested the work; users do the jobs.", SC, 2, ["User needs"],
                  ("single", "client-user", "Which statement is mainly a client / organisational need rather than one end-user task?",
                   [("a", "A learner wants to request a place without visiting reception"), ("b", "Oakfield needs timely capacity information for funding reports"), ("c", "A tutor wants to mark who attended today's class"), ("d", "A learner using a screen reader needs course information that works with their software")],
                   "b", "Funding and capacity visibility are organisational outcomes the client needs. The others are tasks for individual users.", "Keep client outcomes and end-user tasks distinct.")),
                E(3, "Functional or non-functional?", "Jobs versus qualities of the service.", SC, 2, ["Requirements"],
                  ("single", "fnf", "Which statement is mainly a non-functional requirement?",
                   [("a", "Tutors can record learner attendance"), ("b", "Learners can request a place on a course"), ("c", "The service remains usable when venue Wi-Fi is unreliable"), ("d", "Managers can view course capacity")],
                   "c", "Recording attendance and requesting a place are functions. Working under weak Wi-Fi is a quality of the service.", "Non-functional points describe how well or under what conditions the service works.")),
                E(4, "Accessibility as evaluation", "Access is not optional decoration.", SC, 2, ["Accessibility"],
                  ("single", "access-eval", "When comparing two booking options, which accessibility question must be asked?",
                   [("a", "Does the logo use the latest font trend?"), ("b", "Can screen-reader users and people with lower digital confidence complete the request path?"), ("c", "Does the vendor offer branded merchandise?"), ("d", "Is the demo video shot in 4K?")],
                   "b", "The brief requires suitability for different digital confidence and screen-reader users.", "Accessibility changes which option is fit for purpose.")),
                E(5, "Sort need types", "Client, end-user, or constraint.", CL, 3, ["User needs"],
                  ("classify", "need-types", "Classify each statement.",
                   [("client", "Client / organisational need"), ("end-user", "End-user need"), ("constraint", "Constraint")],
                   [("item-1", "Managers need reliable capacity figures during the week", "client"),
                    ("item-2", "A learner needs to find available courses", "end-user"),
                    ("item-3", "Personal data must follow UK GDPR", "constraint"),
                    ("item-4", "A tutor needs to record attendance in class", "end-user"),
                    ("item-5", "The project has a limited budget", "constraint")],
                   "Organisational reporting needs, individual user tasks and constraints are different evaluation inputs.",
                   "Do not treat every statement as the same kind of requirement.")),
                E(6, "Functional vs non-functional", "Separate what it does from how it behaves.", CL, 3, ["Requirements"],
                  ("classify", "fnf-sort", "Classify each requirement.",
                   [("functional", "Functional"), ("non-functional", "Non-functional")],
                   [("item-1", "Learners can request a place", "functional"),
                    ("item-2", "Response times stay acceptable on a library PC", "non-functional"),
                    ("item-3", "Tutors can view relevant class information", "functional"),
                    ("item-4", "Only authorised staff can open learner records", "non-functional"),
                    ("item-5", "Managers can produce funding information", "functional")],
                   "Functional = jobs. Non-functional = performance, security, accessibility and similar qualities.",
                   "Authorisation and performance are qualities, not separate user jobs.")),
                E(7, "Stakeholder conflict", "Whose need is in tension?", CL, 3, ["Stakeholders"],
                  ("classify", "conflict", "For each tension, whose priority is pulling hardest?",
                   [("learners", "Learner access priority"), ("managers", "Manager reporting priority"), ("tutors", "Tutor classroom priority")],
                   [("item-1", "Keep a telephone route even if online reports are slower to digitise", "learners"),
                    ("item-2", "Force all attendance into a live cloud form for same-day funding figures", "managers"),
                    ("item-3", "Allow a paper backup when Wi-Fi drops mid-lesson", "tutors"),
                    ("item-4", "Require smartphone-only booking to cut reception queues", "managers"),
                    ("item-5", "Offer large-print and plain-language course information", "learners")],
                   "Conflicts appear when one group's speed or control harms another's access or classroom reality.",
                   "Name the stakeholder whose priority is driving the pressure.")),
                E(8, "Known, unknown or assumption", "Evaluation must mark honesty.", CL, 3, ["Knowledge gaps"],
                  ("classify", "known-sort", "Classify each statement from an evaluation.",
                   [("known", "Supported by the brief or research"), ("unknown", "Still an unknown"), ("assumption", "Assumption or guess")],
                   [("item-1", "Staff already use Microsoft 365", "known"),
                    ("item-2", "Biometric attendance would be popular with every learner", "assumption"),
                    ("item-3", "The lawful basis for biometric attendance has not been checked", "unknown"),
                    ("item-4", "Learners currently phone or visit reception", "known"),
                    ("item-5", "Every venue already has a shared classroom PC", "assumption")],
                   "Known comes from evidence. Unknowns need research. Assumptions pretend certainty.",
                   "Do not treat a guess as a requirement.")),
                E(9, "Match needs to stakeholders", "Drag each need to who it mainly serves.", MA, 3, ["Stakeholders"],
                  ("match", "need-who", "Match each need to the stakeholder it mainly serves.",
                   [("find", "Find courses and request a place"), ("register", "Record attendance in class"), ("capacity", "See whether a course is full in time")],
                   [("learner", "Learner"), ("tutor", "Tutor"), ("manager", "Manager")],
                   {"find": "learner", "register": "tutor", "capacity": "manager"},
                   "Evaluation fails if every need is treated as a manager need.",
                   "Match the job to the group who would do it.")),
                E(10, "Match quality concerns", "Drag each concern to the quality area.", MA, 3, ["Non-functional"],
                  ("match", "quality-map", "Match each concern to the quality area.",
                   [("screen", "Course pages must work with a screen reader"), ("wifi", "Registers must still work if Wi-Fi drops"), ("who", "Only authorised staff open learner names"), ("train", "Staff should not need a large new training programme")],
                   [("q-access", "Accessibility / usability"), ("q-compat", "Compatibility / resilience"), ("q-sec", "Security / privacy"), ("q-maintain", "Maintainability / training load")],
                   {"screen": "q-access", "wifi": "q-compat", "who": "q-sec", "train": "q-maintain"},
                   "Non-functional evaluation covers access, resilience, privacy and long-term effort.",
                   "Do not collapse every concern into 'features'.")),
                E(11, "Match options to strengths", "Be honest about what each candidate is good at.", MA, 3, ["Solutions"],
                  ("match", "option-strength", "Match each candidate to a realistic strength.",
                   [("sheet", "Improved spreadsheet plus email"), ("forms", "Microsoft Forms / Power Apps on 365"), ("mis", "Specialist adult-learning MIS")],
                   [("s-sheet", "Low new-licence cost if permissions are tightened"), ("s-forms", "Uses accounts staff already know"), ("s-mis", "May offer stronger capacity and reporting tools")],
                   {"sheet": "s-sheet", "forms": "s-forms", "mis": "s-mis"},
                   "Strengths are conditional — still check limits and unknowns.",
                   "Do not invent features the brief never promised.")),
                E(12, "Match options to limitations", "Every candidate has a downside.", MA, 3, ["Solutions"],
                  ("match", "option-limit", "Match each candidate to a realistic limitation.",
                   [("lim-sheet", "Improved spreadsheet plus email"), ("lim-app", "Smartphone-app-only booking"), ("lim-bio", "Biometric attendance")],
                   [("d-sheet", "Other venues may still struggle with timely shared updates"), ("d-app", "Learners with only a library PC may be excluded"), ("d-bio", "Special-category data and lawful basis may be unclear")],
                   {"lim-sheet": "d-sheet", "lim-app": "d-app", "lim-bio": "d-bio"},
                   "Limitations must be specific to Oakfield's users and venues.",
                   "A limitation is not 'it is not exciting enough'.")),
                E(13, "Usability versus decoration", "Usability is task completion.", CL, 3, ["Usability"],
                  ("classify", "usability-sort", "Which changes help usability for Oakfield learners?",
                   [("helps", "Helps usability"), ("hurts", "Hurts or distracts")],
                   [("item-1", "Clear plain-language steps to request a place", "helps"),
                    ("item-2", "Adding animated confetti after every click", "hurts"),
                    ("item-3", "A telephone alternative for lower digital confidence", "helps"),
                    ("item-4", "Hiding the request button behind three marketing videos", "hurts"),
                    ("item-5", "Unexplained icons with no text labels", "hurts")],
                   "Usability is about completing the job with confidence.",
                   "Decoration that hides the task makes usability worse.")),
                E(14, "Compatibility concerns", "Fit with Microsoft 365 and venues.", CL, 3, ["Compatibility"],
                  ("classify", "compat-sort", "Which questions matter for compatibility at Oakfield?",
                   [("matters", "Matters for compatibility"), ("noise", "Noise / not useful")],
                   [("item-1", "Can staff sign in with the Microsoft 365 account they already use?", "matters"),
                    ("item-2", "Does the product include a mascot builder?", "noise"),
                    ("item-3", "Will a live-only register fail when venue Wi-Fi drops?", "matters"),
                    ("item-4", "Is the demo music catchy?", "noise"),
                    ("item-5", "Can tutors export attendance into a format managers already use?", "matters")],
                   "Compatibility means existing accounts, connectivity and ways of working.",
                   "Marketing extras are not compatibility evidence.")),
                E(15, "Security and privacy in evaluation", "Who can see learner data?", MA, 3, ["Security"],
                  ("match", "privacy-map", "Match each privacy concern to why it matters.",
                   [("who", "Who can open learner names"), ("forward", "Forwarding class lists by email"), ("bio", "Storing biometric templates")],
                   [("w-who", "Need-to-know access limits exposure"), ("w-forward", "Uncontrolled copies create breach risk"), ("w-bio", "May be special-category data needing stronger conditions")],
                   {"who": "w-who", "forward": "w-forward", "bio": "w-bio"},
                   "Privacy evaluation names people, data and access.",
                   "Shared learner data is already a risk in the current spreadsheet.")),
                E(16, "Cost beyond licences", "Include training and dual running.", MA, 3, ["Cost"],
                  ("match", "cost-map", "Match each cost type to an Oakfield example.",
                   [("licence", "Licence / subscription"), ("train", "Training / change cost"), ("dual", "Dual-running cost")],
                   [("ex-licence", "Annual fee for a specialist MIS"), ("ex-train", "Half a day teaching staff a new attendance tool"), ("ex-dual", "Keeping the paper diary while the new form beds in")],
                   {"licence": "ex-licence", "train": "ex-train", "dual": "ex-dual"},
                   "Total cost includes people time, not only the price list.",
                   "Limited budget makes hidden costs important.")),
                E(17, "Conflicting needs scenario", "Managers want speed; learners need access.", SC, 2, ["Stakeholders"],
                  ("single", "conflict-q", "Managers want same-day digital attendance for funding. Tutors at weak-Wi-Fi venues need a backup. What is the strongest justified compromise?",
                   [("a", "Ignore tutors and force live-only entry everywhere"), ("b", "Provide a digital register with an agreed offline/paper backup that is uploaded when connectivity returns"), ("c", "Abandon funding reports"), ("d", "Stop recording attendance")],
                   "b", "A justified compromise protects classroom reality without abandoning organisational reporting.", "Do not sacrifice one stakeholder completely without a plan.")),
                E(18, "Scalability and performance", "Think venues and concurrent use.", SC, 2, ["Performance"],
                  ("single", "scale", "Which question best probes scalability for Oakfield?",
                   [("a", "Will the system still behave if several venues take registers around the same evening peak?"), ("b", "Does the login screen use a gradient?"), ("c", "Is the vendor's office plant healthy?"), ("d", "How many fonts can the homepage load?")],
                   "a", "Oakfield runs across venues. Peak concurrent use and weak connectivity matter.", "Scalability is about load and growth, not decoration.")),
                E(19, "List four criteria", "Show you can start an evaluation.", WR, 4, ["Evaluation criteria"],
                  ("short", "criteria", "List four criteria for comparing solutions in this Oakfield project.", "1. ... 2. ... 3. ... 4. ...", "Include users/purpose, cost/training, risk/privacy, accessibility, compatibility or maintainability.", 40)),
                E(20, "Two candidates table", "Strength, limitation, unknown.", WR, 4, ["Solutions"],
                  ("short", "table", "For two candidates, record one strength, one limitation and one unknown each.", "Candidate 1: ... Candidate 2: ...", "Include the current way of working as one candidate if useful. Be honest about unknowns.", 100)),
                E(21, "Weaker for smartphone-free learners", "Name the candidate and why.", WR, 4, ["Accessibility"],
                  ("short", "users", "Which candidate is weaker for a learner who does not own a smartphone, and why?", "Candidate: ... Why: ...", "App-only routes usually fail this test; say so clearly.", 60)),
                E(22, "Justify a recommendation", "Conflict between manager speed and learner access.", WR, 4, ["Justification"],
                  ("short", "recommend", "Managers want app-only booking to cut queues. Recommend keep/change the telephone route and justify for learners and managers.", "Recommendation: ... Learners: ... Managers: ...", "A good answer protects access while still improving digital capture where possible.", 90)),
                E(23, "Maintainability concern", "Who supports it next year?", WR, 4, ["Maintainability"],
                  ("short", "maintain", "Explain one maintainability concern when choosing between a specialist MIS and extending Microsoft 365.", "Maintainability concern: ...", "Think about skills staff already have, vendor dependency and what happens if the expert leaves.", 70)),
                E(24, "Security/privacy trade-off", "Convenience versus protection.", WR, 4, ["Security"],
                  ("short", "tradeoff", "Describe one security or privacy trade-off Oakfield might face when moving attendance online.", "Trade-off: ...", "Example: easier sharing versus tighter access control and logging.", 70)),
                E(25, "Unknown action", "Close a gap with a concrete next step.", WR, 4, ["Knowledge gaps"],
                  ("short", "unknown", "Write one unknown from your evaluation and one action that would close it.", "Unknown: ... Action: ...", "Actions: check ICO/DPO, interview tutors, review permissions, pilot in one venue.", 60)),
                E(26, "Good GDPR next action", "Reliable sources, not polls.", SC, 2, ["Privacy"],
                  ("single", "gdpr-next", "A good next action for an unknown about GDPR and biometrics is:",
                   [("a", "Assume it is fine because other colleges do it"), ("b", "Check ICO / centre DPO guidance and record the source"), ("c", "Skip the topic until after coding"), ("d", "Ask a social media poll")],
                   "b", "Legal and data questions need reliable sources, not assumption.", "Record the gap and a concrete research action.")),
                E(27, "Performance vs features", "Prioritise under limited budget.", WR, 4, ["Performance"],
                  ("short", "perf", "Under a limited budget, why might reliable performance on weak venue Wi-Fi matter more than adding another marketing feature?", "It matters more because...", "Link to tutors taking registers and learners completing requests.", 70)),
                E(28, "Evaluation summary", "State recommendation with criteria used.", WR, 4, ["Justification"],
                  ("short", "summary", "In three to five sentences, summarise how you would evaluate two Oakfield candidates and what would make you change recommendation.", "I would evaluate... I would change if...", "Name users, at least two non-functional concerns, and one unknown that could reverse the choice.", 100)),
            ],
        },
        {
            "title": "Lesson 3: Regulation and knowledge gaps",
            "summary": "Identify guidelines and regulations that may apply, practise spotting assumptions, and plan how to close personal knowledge gaps.",
            "exercises": [
                E(1, "Why UK GDPR matters for attendance", "Attendance data can identify people.", SC, 2, ["Data protection"],
                  ("single", "q1", "Why does UK GDPR matter when choosing an attendance technology?",
                   [("a", "It only applies to banks"), ("b", "Attendance data can be personal data and some biometrics are special category data"), ("c", "It bans all cloud software"), ("d", "It replaces accessibility law")],
                   "b", "Registers identify people. Some biometric data needs extra conditions.", "Data protection shapes which options are even legal.")),
                E(2, "Accessibility obligation", "The brief already raises access needs.", SC, 2, ["Accessibility"],
                  ("single", "access-law", "Which statement best reflects Oakfield's accessibility obligation for a public digital service?",
                   [("a", "Only managers need accessible screens"), ("b", "The service should work for screen-reader users and people with different digital confidence / language needs"), ("c", "Accessibility is optional if the logo looks friendly"), ("d", "Accessibility only applies to printed posters")],
                   "b", "The brief requires suitability for screen readers, digital confidence and English as an additional language.", "Accessibility is part of fitness for purpose.")),
                E(3, "Copyright / IP caution", "Do not paste unlicensed content into a proposal.", SC, 2, ["Copyright"],
                  ("single", "ip", "Which action shows appropriate respect for copyright when researching solutions?",
                   [("a", "Copying a vendor's entire help site into your report without attribution"), ("b", "Summarising findings in your own words and naming the source"), ("c", "Using a pirated software crack to 'test' a product"), ("d", "Claiming a competitor's screenshot as your own design")],
                   "b", "Summarise and attribute. Do not steal content or use illegal software.", "IP discipline is part of professional practice.")),
                E(4, "Security obligation", "Protect learner data in transit and at rest.", SC, 2, ["Security"],
                  ("single", "sec", "Which practice best matches a basic security obligation for Oakfield learner records?",
                   [("a", "Share one spreadsheet password with the whole staff WhatsApp group"), ("b", "Limit access to people who need it and avoid uncontrolled forwarding of learner lists"), ("c", "Email full registers to personal accounts for convenience"), ("d", "Post attendance photos publicly to 'celebrate learning'")],
                   "b", "Need-to-know access and controlled sharing protect personal data.", "Convenience is not a reason to widen access.")),
                E(5, "Regulation or preference?", "Separate rules from taste.", CL, 3, ["Regulation"],
                  ("classify", "reg-pref", "Classify each statement.",
                   [("regulation", "Guideline / legal consideration"), ("preference", "Preference or taste")],
                   [("item-1", "Personal data must be handled in accordance with UK GDPR", "regulation"),
                    ("item-2", "I prefer purple buttons", "preference"),
                    ("item-3", "Public digital services should be accessible to disabled users", "regulation"),
                    ("item-4", "The team likes a vendor's advertising jingle", "preference"),
                    ("item-5", "Centre acceptable-use rules may limit how generative AI is used", "regulation")],
                   "Regulations and centre policies constrain design. Taste does not.",
                   "Do not treat brand preference as a legal duty.")),
                E(6, "Assumption or knowledge gap?", "Honesty about what you do not know.", CL, 3, ["Knowledge gaps"],
                  ("classify", "assume-gap", "Classify each statement.",
                   [("assumption", "Assumption presented as fact"), ("gap", "Honest knowledge gap"), ("known", "Supported by the brief")],
                   [("item-1", "Every learner owns a smartphone", "assumption"),
                    ("item-2", "I do not yet know who can edit the shared spreadsheet", "gap"),
                    ("item-3", "Some venues have unreliable Wi-Fi", "known"),
                    ("item-4", "Biometrics would definitely be popular with all adults", "assumption"),
                    ("item-5", "I need DPO advice before recommending biometrics", "gap")],
                   "Assumptions invent certainty. Gaps admit missing knowledge. Known points come from the brief.",
                   "Mark assumptions so they can be tested.")),
                E(7, "Which guidance applies?", "Map topics to likely guidance.", CL, 3, ["Guidelines"],
                  ("classify", "guidance", "Which guidance area is the first place to look?",
                   [("data", "Data protection / privacy"), ("access", "Accessibility / Equality"), ("ai", "Centre AI / acceptable use"), ("ip", "Copyright / licensing")],
                   [("item-1", "Storing fingerprint templates for attendance", "data"),
                    ("item-2", "Whether course pages work with a screen reader", "access"),
                    ("item-3", "Whether staff may paste learner data into a public chatbot", "ai"),
                    ("item-4", "Reusing a vendor diagram in a learner proposal", "ip"),
                    ("item-5", "Who is allowed to export a full class list", "data")],
                   "Different issues point to different professional guidance.",
                   "Do not use one vague 'legal' bucket for everything.")),
                E(8, "Emerging vs established (regulation lesson)", "Context again for technology claims.", CL, 3, ["Emerging technology"],
                  ("classify", "emerg-estab", "Classify each technology for Oakfield admin.",
                   [("emerging", "Emerging in this context"), ("established", "Established in this context")],
                   [("item-1", "Paper diary and shared spreadsheet for bookings", "established"),
                    ("item-2", "Biometric attendance for adult learners", "emerging"),
                    ("item-3", "Microsoft 365 email already used by staff", "established"),
                    ("item-4", "AI course matching for learners with low digital confidence", "emerging"),
                    ("item-5", "Telephone enquiries to reception", "established")],
                   "Regulation questions often bite hardest on emerging options.",
                   "Established tools still need GDPR and access controls.")),
                E(9, "Match issue to guidance", "Drag each issue to the right starting point.", MA, 3, ["Guidelines"],
                  ("match", "issue-guide", "Match each issue to the guidance you would check first.",
                   [("bio", "Fingerprint attendance"), ("screen", "Screen-reader access to course lists"), ("chat", "Pasting registers into a public AI chat"), ("copy", "Copying a vendor white paper into a submission")],
                   [("g-dpo", "ICO / DPO / UK GDPR guidance"), ("g-access", "Accessibility / Equality Act expectations"), ("g-ai", "Centre AI / acceptable-use policy"), ("g-ip", "Copyright / attribution rules")],
                   {"bio": "g-dpo", "screen": "g-access", "chat": "g-ai", "copy": "g-ip"},
                   "Start with the guidance that matches the harm.",
                   "Do not invent a single 'internet law' answer.")),
                E(10, "Match gap to closing action", "Every gap needs a next step.", MA, 3, ["Knowledge gaps"],
                  ("match", "gap-action", "Match each knowledge gap to a sensible closing action.",
                   [("gap-law", "Unsure whether biometrics need special-category conditions"), ("gap-users", "Unsure how many learners lack a smartphone"), ("gap-wifi", "Unsure what tutors do when Wi-Fi fails")],
                   [("act-dpo", "Ask the DPO / read ICO guidance and record the source"), ("act-count", "Ask reception for enquiry channels or run a short learner access check"), ("act-tutor", "Interview tutors about the offline workaround")],
                   {"gap-law": "act-dpo", "gap-users": "act-count", "gap-wifi": "act-tutor"},
                   "A gap without an action stays an assumption later.",
                   "Pick actions that produce evidence.")),
                E(11, "Match professional roles", "Know who to ask.", MA, 3, ["Professional practice"],
                  ("match", "who-ask", "Match each question to the best person or role to ask.",
                   [("q-data", "Is this lawful basis acceptable for attendance data?"), ("q-teach", "What happens in class if the register tool fails?"), ("q-fund", "When do funding reports need attendance figures?")],
                   [("role-dpo", "Data protection officer / nominated privacy lead"), ("role-tutor", "Tutor who takes registers"), ("role-manager", "Manager responsible for funding reports")],
                   {"q-data": "role-dpo", "q-teach": "role-tutor", "q-fund": "role-manager"},
                   "Professional practice includes asking the right role.",
                   "Do not expect tutors to give formal legal advice.")),
                E(12, "Match risk to regulation theme", "Connect harms to themes.", MA, 3, ["Risk"],
                  ("match", "risk-theme", "Match each risk to the regulation theme it mainly raises.",
                   [("r-share", "Learner names forwarded to staff who do not need them"), ("r-exclude", "App-only booking blocks library-PC users"), ("r-train", "No time to train staff on a new system")],
                   [("t-privacy", "Data protection / privacy"), ("t-access", "Accessibility / inclusion"), ("t-ops", "Operational / training obligation")],
                   {"r-share": "t-privacy", "r-exclude": "t-access", "r-train": "t-ops"},
                   "Naming the theme helps you find the right guidance.",
                   "Training load is an operational duty even when it is not a statute name.")),
                E(13, "Personal knowledge gap", "Admit what you do not know yet.", SC, 2, ["Knowledge gaps"],
                  ("single", "personal", "Which statement is a healthy personal knowledge gap for a T Level learner on this project?",
                   [("a", "I already know every UK GDPR article by heart, so I will not check sources"), ("b", "I am not yet sure how special-category biometric rules apply, so I will check ICO / DPO guidance"), ("c", "Legal topics are irrelevant to software projects"), ("d", "I will guess the lawful basis to save time")],
                   "b", "Honest gaps plus a research action are professional. Guessing is not.", "You are not expected to be a lawyer; you are expected to find reliable guidance.")),
                E(14, "Poor way to close a gap", "Reject unsafe shortcuts.", SC, 2, ["Knowledge gaps"],
                  ("single", "poor-close", "Which is a poor way to close a knowledge gap about learner data?",
                   [("a", "Read centre policy and ask the nominated privacy lead"), ("b", "Paste a full class list into a public chatbot to 'ask AI'"), ("c", "Check ICO guidance and record the URL/date"), ("d", "Ask a manager how funding reports use attendance")],
                   "b", "Putting personal data into a public tool can create a new breach risk.", "Closing a gap must not create a bigger privacy problem.")),
                E(15, "Why regulation appears in evaluation", "Not an afterthought.", SC, 2, ["Regulation"],
                  ("single", "why-reg", "Why should regulation appear during solution evaluation, not only after coding?",
                   [("a", "Because lawyers enjoy late surprises"), ("b", "Because some options may be unlawful or high-risk for Oakfield's data and users"), ("c", "Because regulation bans all digital services"), ("d", "Because fonts are regulated in adult learning")],
                   "b", "Illegal or high-risk options should be filtered before deep design effort.", "Regulation is a comparison criterion.")),
                E(16, "Security misstep", "Spot unsafe practice.", SC, 2, ["Security"],
                  ("single", "misstep", "Which team behaviour is a security misstep while researching Oakfield solutions?",
                   [("a", "Using anonymised examples in notes"), ("b", "Emailing a spreadsheet of real learner names to a personal Gmail to work at home"), ("c", "Storing research links in the team notebook"), ("d", "Redacting surnames from screenshots used in class")],
                   "b", "Moving real learner personal data to personal email widens access without control.", "Protect live personal data during research.")),
                E(17, "Name two regulations/guidelines", "Say what they might affect.", WR, 4, ["Regulation"],
                  ("short", "rules", "Name two guidelines or regulations that may apply to Oakfield's service, and what they might affect.", "1. ... affects ... 2. ...", "Examples: UK GDPR, accessibility expectations, centre AI policy, copyright.", 70)),
                E(18, "Personal gap and action", "Plan your own next research step.", WR, 4, ["Knowledge gaps"],
                  ("short", "plan", "Write one knowledge gap you still have and one action to address it (source, person, or practice task).", "Gap: ... Action: ...", "Keep it specific to Oakfield: data, access, Wi-Fi, AI policy, or similar.", 60)),
                E(19, "Explain a knowledge gap risk", "What goes wrong if you ignore it?", WR, 4, ["Knowledge gaps"],
                  ("short", "gap-risk", "Choose one knowledge gap. Explain how ignoring it could lead to a weak or harmful recommendation.", "If I ignore... the recommendation could...", "Link to exclusion, unlawful processing, failed registers, or wasted budget.", 80)),
                E(20, "Accessibility gap example", "Connect users to actions.", WR, 4, ["Accessibility"],
                  ("short", "access-gap", "Describe one accessibility-related knowledge gap for Oakfield and how you would close it.", "Gap: ... Close it by...", "Example: whether course content has been tested with a screen reader; action: check with access lead / test with assistive tech.", 70)),
                E(21, "Data-protection explanation", "Use attendance or bookings.", WR, 4, ["Data protection"],
                  ("short", "dp-explain", "Explain why booking and attendance records need data-protection thinking at Oakfield.", "They need data-protection thinking because...", "Mention personal data, who can see it, and possible special-category issues for biometrics.", 70)),
                E(22, "IP in research notes", "Professional attribution.", WR, 4, ["Copyright"],
                  ("short", "ip-write", "How should you handle vendor diagrams or wording when writing your Oakfield research notes?", "I should...", "Summarise in your own words, attribute the source, and avoid pasting large copyrighted chunks as if they were yours.", 60)),
                E(23, "Justify emerging with regulation", "Link novelty to extra checks.", WR, 4, ["Emerging technology"],
                  ("short", "why", "Pick one emerging technology for Oakfield. Explain why regulation or guidance needs extra attention compared with an established option.", "Technology: ... Extra attention because...", "Biometrics and AI often raise privacy or acceptable-use questions that paper processes do not.", 80)),
                E(24, "Assumption challenge", "Rewrite an assumption as a question.", WR, 4, ["Knowledge gaps"],
                  ("short", "challenge", "Rewrite this assumption as a research question: 'All Oakfield learners are happy to use a smartphone app.'", "Research question: ...", "Ask about device access, confidence, and whether a non-app route is still needed.", 40)),
                E(25, "Professional guidance route", "Show the path you would take.", WR, 4, ["Professional practice"],
                  ("short", "route", "A teammate wants to use generative AI to draft learner emails including names and course choices. What guidance would you check, and what would you advise meanwhile?", "Guidance: ... Advice meanwhile: ...", "Centre AI policy and data protection: do not put personal data into unapproved tools.", 80)),
                E(26, "Security obligation in design", "One concrete control.", WR, 4, ["Security"],
                  ("short", "control", "Propose one security or privacy control Oakfield should require in any new attendance solution.", "Control: ...", "Examples: role-based access, audit logs, no shared passwords, retention limits.", 50)),
                E(27, "Prioritise which gap to close", "Limited time this week.", SC, 2, ["Knowledge gaps"],
                  ("single", "prioritise", "You only have time to close one gap before recommending biometrics. Which gap should come first?",
                   [("a", "Whether the vendor's logo uses pantone colours"), ("b", "Whether lawful basis / special-category conditions are understood with DPO or ICO guidance"), ("c", "Whether the demo uses a fun animation"), ("d", "Whether the sales person prefers tea or coffee")],
                   "b", "Legal and data conditions can stop the option entirely. Branding does not.", "Prioritise gaps that can invalidate the recommendation.")),
                E(28, "Week close: regulation and gaps", "Bring the threads together.", WR, 4, ["Regulation"],
                  ("short", "close", "In your own words, explain how regulations/guidelines and personal knowledge gaps should influence Oakfield solution choices this week.", "Regulations/guidelines should... Knowledge gaps should...", "Say that illegal/high-risk options are filtered early, and unknowns get actions before confident recommendations.", 90)),
            ],
        },
    ],
    "homework": {
        "title": "Homework: one emerging technology with a source",
        "summary": "Research one emerging technology relevant to Oakfield. Note one benefit, one risk and one source.",
        "id_suffix": "emerging",
        "minutes": 25,
        "topics": ["Emerging technology", "Sources"],
        "blocks": [
            ("h2", "Independent study"),
            ("p", "intro", "Choose one emerging technology that could affect bookings, attendance or course information at Oakfield. Do not invent a fictional start-up as the only evidence. Short notes are enough."),
            ("short", "tech", "Name the technology, one benefit and one risk for Oakfield's users.", "Technology: ... Benefit: ... Risk: ...", 40),
            ("short", "source", "Give the source you used (title, organisation, year or date). Why is it usable for a proposal?", "Source: ... I would use it because...", "A regulator page, similar-provider write-up or centre policy is stronger than a slogan-only advert.", 40),
            ("short", "gap", "Name one thing you still do not know, and one action to close that gap.", "Unknown: ... Action: ...", 30),
        ],
    },
}
