"""Week 5 teaching blocks for the T Level OS curriculum generator.

Imported by generate-os-curriculum.py.

Week 5 taught lessons use one top-level activity per exercise
(approximately 9 per lesson). Count activities, not items on a
classification or drag-drop board.

LO1 / 1.1: schedule tasks and milestones; allocate resources and estimate
costs; select a language using taught criteria.

Do not re-teach Week 3 to 4 content (FR/NFR, KPIs, acceptance, decomposition).
"""


def E(n, title, summary, kind, minutes, topics, *blocks):
    return {
        "id": f"ex-{n:02d}",
        "title": title,
        "summary": summary,
        "type": kind,
        "minutes": minutes,
        "topics": list(topics),
        "blocks": list(blocks),
    }


SC = "Single choice"
CL = "Classification"
MA = "Matching"
WR = "Written response"

WEEK_5 = {
    "n": 5,
    "title": "Scheduling, Resources, Cost and Language Choice",
    "wc": "2026-09-28",
    "phase": "analyse-problem",
    "practice": "LO1 / 1.1: schedule tasks and milestones; allocate resources and estimate costs; select a language using taught criteria",
    "lo_ids": ["lo1"],
    "outcomes": [
        ("w5-schedule", "Schedule tasks, subtasks and milestones"),
        ("w5-resources-cost", "Allocate resources and estimate project costs"),
        ("w5-language", "Select a language using the taught criteria"),
    ],
    "lessons": [
        {
            "title": "Lesson 1: Milestone plan",
            "summary": "Distinguish tasks, subtasks and milestones; sequence work with dependencies, testing and client review; produce a small schedule.",
            "exercises": [
                E(1, "What is a milestone?", "A checkpoint of completed work, not every daily action.", SC, 2, ["Milestones"],
                  ("single", "ms", "In a software project schedule, which statement best describes a milestone?",
                   [("a", "Any meeting held during the project, whether or not work is finished"),
                    ("b", "A named checkpoint that shows a meaningful piece of work is complete and can be checked"),
                    ("c", "The first task in every project, always identical regardless of the product"),
                    ("d", "A list of every email sent between the developer and the client")],
                   "b", "Milestones mark progress you can check. Routine meetings and messages are not milestones by themselves.",
                   "A milestone should be something you can check is finished, not just a meeting or an email.")),
                E(2, "Task or subtask?", "Subtasks sit under a larger piece of work.", SC, 2, ["Tasks"],
                  ("single", "sub", "A college is building a room-booking web form for staff. Which item is most clearly a subtask of 'build the booking form'?",
                   [("a", "Publish the finished booking service to every campus across the region"),
                    ("b", "Add validation so a room cannot be requested for a date that is already taken"),
                    ("c", "Write the annual governance report for the college board"),
                    ("d", "Replace the college's public website branding in a separate redesign project")],
                   "b", "Validation is work inside building the form. Region-wide publish, board reports and branding projects sit outside that task.",
                   "Choose the item that helps finish building the form, not a different project.")),
                E(3, "Classify schedule items", "Sort tasks, subtasks and milestones for a short project.", CL, 4, ["Scheduling"],
                  ("classify", "sort-items", "Classify each item for a gym membership join-and-pay pilot.",
                   [("task", "Task"), ("subtask", "Subtask"), ("milestone", "Milestone")],
                   [("item-1", "Design the membership join screen", "task"),
                    ("item-2", "Add a check so under-16s must enter a parent contact", "subtask"),
                    ("item-3", "First usable join-and-pay flow ready for a staff trial", "milestone"),
                    ("item-4", "Draft the payment confirmation email wording", "subtask"),
                    ("item-5", "End-to-end test of join, pay and confirmation signed off", "milestone")],
                   "Tasks are chunks of work. Subtasks are steps inside a task. Milestones are checkable completion points.",
                   "An email draft is usually a subtask. A signed-off trial-ready flow is a milestone.")),
                E(4, "Match schedule terms", "Link each term to what it means in planning.", MA, 3, ["Scheduling"],
                  ("match", "terms", "Match each scheduling term to its meaning.",
                   [("dep", "Dependency"), ("par", "Parallel work"), ("slip", "Slip")],
                   [("m-dep", "One piece of work cannot usefully start until another has produced a needed output"),
                    ("m-par", "Two pieces of work can progress in the same period because they do not block each other"),
                    ("m-slip", "A planned date or checkpoint moves later than agreed")],
                   {"dep": "m-dep", "par": "m-par", "slip": "m-slip"},
                   "Dependencies force order. Parallel work saves calendar time when resources allow. Slip means the plan moved.",
                   "Do not treat every delay as a brand-new task.")),
                E(5, "Spot the real dependency", "Choose the dependency that actually blocks progress.", SC, 3, ["Dependencies"],
                  ("single", "dep", "An event-booking team is preparing a first pilot. Which statement describes a real dependency?",
                   [("a", "Writing the customer FAQ about how payment references appear should wait until the payment integration behaviour is known"),
                    ("b", "Choosing a footer colour must wait until the domain name is renewed in five years' time"),
                    ("c", "User interviews and drafting the privacy notice must always be done by the same person on the same afternoon"),
                    ("d", "Interface sketches cannot start until the final marketing video for launch week is finished")],
                   "a", "The FAQ needs accurate payment behaviour. The other options invent false constraints or confuse preference with dependency.",
                   "Look for what information or output one task truly needs from another.")),
                E(6, "Sequential or parallel?", "Judge what can safely overlap.", CL, 5, ["Parallel work"],
                  ("classify", "seq-par", "For a small online-retailer checkout project, classify each pair.",
                   [("sequential", "Must be sequential"), ("parallel", "Can run in parallel")],
                   [("item-1", "Basket field names are still being agreed. The basket API that will use those names is about to be coded.", "sequential"),
                    ("item-2", "A writer is drafting help-centre articles. Developers are building the basket screen. Neither waits on the other's unfinished file.", "parallel"),
                    ("item-3", "Payment sandbox tests are incomplete. The team wants to take live card charges from customers.", "sequential"),
                    ("item-4", "Product photos are being shot. A different developer is laying out the product list page that will display those photos later.", "parallel"),
                    ("item-5", "The go-live checklist is not yet agreed. The team is ready to switch on real card charges.", "sequential")],
                   "If one unfinished output is an input to the other, keep them sequential. Independent owners with no shared unfinished input can run in parallel.",
                   "Live payments should not start while tests or go-live checks are still open.")),
                E(7, "Analyse a weak schedule", "Name what the plan leaves out and propose a fix.", WR, 7, ["Milestones", "Schedule"],
                  ("p", "weak", "A college room-booking pilot plan currently lists only: design screens, then build screens, then launch to staff."),
                  ("short", "gap", "Identify two serious weaknesses in that plan for a first pilot.",
                   "Weakness 1: ...\nWeakness 2: ...",
                   "Think about checking quality, staff feedback, and what 'launch' skips.", 50),
                  ("short", "fix", "Rewrite the plan as four to six ordered checkpoints that fix those weaknesses. Briefly explain one ordering decision.",
                   "1. ...\n2. ...\n3. ...\n4. ...\n(5. ...)\n(6. ...)\nJustification: ...",
                   "Include testing and a staff or client review before wide launch. Keep it short.", 80)),
                E(8, "Build a schedule for an event-booking pilot", "Sequence tasks, mark dependencies, parallel work, milestones and slip impact.", WR, 18, ["Schedule", "Dependencies", "Milestones"],
                  ("p", "scenario", "Riverbank Arts wants a small first pilot of an online event-booking system. Members request a place; staff confirm it. Use the task list below. Do not invent a huge programme."),
                  ("p", "tasks", "Tasks (not yet ordered): confirm client needs for the pilot; produce interface designs; design data storage; create the database; build account sign-in; build booking request screens; integrate front end and back end; test core booking flow; fix issues found in testing; client review of the pilot; release the pilot to a small staff group."),
                  ("short", "order", "TASK ORDER\nPut the tasks in a sensible order.\nYou may group closely related steps if you explain why.",
                   "1. ...\n2. ...\n3. ...\n4. ...\n5. ...\n6. ...\n7. ...\n8. ...\n9. ...\n10. ...\n11. ...",
                   "Needs and designs usually come before build. Database before features that store data. Test and fix before wide release. Client review before or with release of a pilot.", 120),
                  ("short", "deps", "DEPENDENCIES\nName two dependencies.\nFor each, say what depends on what and why.",
                   "1. ___ depends on ___ because...\n2. ___ depends on ___ because...",
                   "Strong answers name a needed output (for example schema, working sign-in, or test results), not just 'it feels better'.", 80),
                  ("short", "parallel", "PARALLEL WORK\nName at least two activities that could happen at the same time.\nSay why they do not block each other.",
                   "___ and ___ could happen together because...",
                   "Pick work with different owners or unfinished inputs that are not shared.", 50),
                  ("short", "miles", "MILESTONES\nAdd three checkable milestones (not day-to-day tasks).\nInclude testing or client review somewhere sensible.",
                   "Milestone 1: ...\nMilestone 2: ...\nMilestone 3: ...",
                   "Examples of shape: designs agreed; core booking flow passes tests; client signs off pilot.", 60),
                  ("short", "slip", "IF SOMETHING SLIPS\nChoose one important task that could be delayed by one week.\nWhat happens to later work and to the pilot date?",
                   "If ___ slips by one week, then...",
                   "Name at least one knocked-on task or milestone, not only 'the project is late'.", 50),
                  ("short", "why", "JUSTIFICATION\nExplain two scheduling decisions you made.",
                   "Decision 1: ...\nDecision 2: ...",
                   "Tie each decision to a dependency, parallel choice, or where testing and review sit.", 70)),
                E(9, "Judgement: protect the pilot date", "Choose the better response when design work slips.", SC, 3, ["Judgement"],
                  ("single", "slip-j", "Interface designs for the Riverbank pilot slip by one week. Build was due to start next Monday. Which response is best for a small first increment?",
                   [("a", "Keep the original release date and cut all testing so build can finish on the old calendar"),
                    ("b", "Move build start, protect a short test-and-fix window, and renegotiate the pilot date or reduce pilot scope with the client"),
                    ("c", "Cancel the project and restart next year with a different venue"),
                    ("d", "Ignore the slip and tell developers to start coding from memory without designs")],
                   "b", "A slip needs an honest plan change: protect checking quality and agree date or scope with the client. Cutting all testing or coding blind increases risk.",
                   "Prefer an honest plan change over cutting all testing or coding without designs.")),
            ],
        },
        {
            "title": "Lesson 2: Resources and a costed outline",
            "summary": "Identify people, tools and services; produce a costed outline against a budget; justify resource trade-offs.",
            "exercises": [
                E(1, "What counts as a project resource?", "Resources are what the project consumes or needs.", SC, 2, ["Resources"],
                  ("single", "res", "Which item is most clearly a project resource for a community-centre booking site?",
                   [("a", "Four weeks of developer time booked against the project"),
                    ("b", "The colour of the centre's front door, which marketing already chose last year"),
                    ("c", "A hope that bookings will rise after launch, with no staff or tools attached"),
                    ("d", "The postcode of a neighbouring town that is not in scope")],
                   "a", "People time allocated to the project is a core resource. Door colour, vague hopes and out-of-scope geography are not what you cost here.",
                   "Look for what the project uses up: people, kit, licences or services.")),
                E(2, "Classify resource types", "People, hardware, software and services.", CL, 4, ["Resources"],
                  ("classify", "res-type", "Classify each resource for a transport-app pilot.",
                   [("people", "People"), ("hardware", "Hardware"), ("software", "Software or licences"), ("service", "External service")],
                   [("item-1", "Two part-time developers for six weeks", "people"),
                    ("item-2", "Three Android test phones", "hardware"),
                    ("item-3", "Map API usage fees billed by call volume", "service"),
                    ("item-4", "IDE seats and cloud hosting subscription", "software"),
                    ("item-5", "Accessibility tester booked for two days", "people")],
                   "People do the work. Hardware is physical kit. Software or licences are tools you run. Services are bought capability such as APIs.",
                   "Do not put every cost under 'software'.")),
                E(3, "One-off or recurring cost?", "Timing of spend matters in a proposal.", SC, 3, ["Cost"],
                  ("single", "timing", "A gym membership app will send booking reminders through a paid SMS provider. The provider invoices the centre at the end of each month for messages sent that month. How should that SMS spend be treated in a costed outline?",
                   [("a", "As a one-off set-up fee only, because the first message proves the integration works"),
                    ("b", "As a recurring operating cost for as long as reminders stay switched on"),
                    ("c", "As free, because members already pay a membership fee to the gym"),
                    ("d", "As a milestone name rather than a cost line")],
                   "b", "Monthly usage invoices continue after launch. Membership fees paid by customers do not cancel the centre's SMS bill.",
                   "Check whether the spend stops after set-up or keeps appearing while the feature runs.")),
                E(4, "Match cost ideas to examples", "Connect cost types to concrete items.", MA, 3, ["Cost"],
                  ("match", "cost-ex", "Match each cost idea to the best example for an event-booking project.",
                   [("one", "One-off cost"), ("rec", "Recurring cost"), ("hidden", "Easy-to-miss cost")],
                   [("e-one", "Paying for the domain name for the first year of the pilot"),
                    ("e-rec", "Monthly hosting while the booking site stays live"),
                    ("e-hidden", "Reception staff time to learn the new confirmation process")],
                   {"one": "e-one", "rec": "e-rec", "hidden": "e-hidden"},
                   "Domain purchase is typically up-front for the year. Hosting repeats. Training time is real even when nobody sends an invoice.",
                   "Hidden costs are still costs.")),
                E(5, "Missing cost in a thin estimate", "Find a serious omission, not a joke option.", SC, 3, ["Cost"],
                  ("single", "missing", "A small online retailer's increment-1 estimate lists developer days, hosting, and the payment-provider fee. Nothing else. Which omission is most serious for a first launch?",
                   [("a", "No line for a celebrity endorsement campaign next year"),
                    ("b", "No people time for testing and fixing defects before customers pay"),
                    ("c", "No budget for restocking the office biscuit tin"),
                    ("d", "No international shipping cost for a product line they have already decided not to sell")],
                   "b", "Testing and defect fixing consume people time and are often left out of thin estimates. The other options are not necessary for this increment.",
                   "Look for work that must happen before real customers are affected.")),
                E(6, "Budget pressure on a first increment", "Choose the better cut when money is tight.", SC, 3, ["Trade-offs"],
                  ("single", "budget", "A community centre has £2,000 for a first booking increment. Staff already use Microsoft 365. Which option best fits a limited first increment?",
                   [("a", "Build custom native apps for six phone platforms before any shared web request form exists"),
                    ("b", "Reuse existing Microsoft 365 tools for a simple request-and-review form, and cost a later phase for richer features"),
                    ("c", "Spend the whole budget on a marketing agency and delay any booking workflow until next year"),
                    ("d", "Buy biometric turnstiles for every room before any booking process is agreed")],
                   "b", "A first increment should stay inside budget and reuse tools that already fit. Multi-platform native apps, marketing-only spend and turnstiles blow or miss the booking goal.",
                   "Prefer a scoped early increment over an all-features launch.")),
                E(7, "Strong or weak cost assumption?", "Assumptions must be stated and checkable.", CL, 4, ["Assumptions"],
                  ("classify", "assume", "Classify each statement for a college booking estimate.",
                   [("strong", "Useful stated assumption"), ("weak", "Weak or vague assumption")],
                   [("item-1", "We assume one developer at four days per week for three weeks", "strong"),
                    ("item-2", "We assume the work will somehow stay cheap without saying how", "weak"),
                    ("item-3", "We assume Microsoft 365 licences are already paid by the college this year", "strong"),
                    ("item-4", "We assume nobody on reception will need any walkthrough of the new process", "weak"),
                    ("item-5", "We assume accessibility testing needs two paid days", "strong")],
                   "Useful assumptions name roles, days, licences or test effort. Vague hope or silent training cuts are weak.",
                   "If the assumption is wrong, the plan should change.")),
                E(8, "Costed plan against a real budget", "Allocate days, calculate totals, fit £2,500, state assumptions and a change.", WR, 18, ["Cost", "Resources", "Budget"],
                  ("p", "scenario", "Greenfield Community Events wants a first online event-request form. Staff still confirm places. There are no card payments in increment 1. Budget for increment 1 is £2,500. Teaching rates (not real market quotes): Developer £180/day; Designer £150/day; Tester £140/day; cloud hosting £35; domain £15; form or software licence £40."),
                  ("p", "draft", "A colleague's first draft request: 10 developer days, 5 designer days, 3 tester days, plus hosting, domain and licence. That draft is over budget. Produce a revised costed plan that fits £2,500. If you think it cannot fit, say what you would tell the client."),
                  ("short", "table", "Complete a costed table for your revised plan. Show days or quantity, unit cost and line total for people and other costs.",
                   "Resource | Days or qty | Unit cost | Line total\nDeveloper | ... | £180 | ...\nDesigner | ... | £150 | ...\nTester | ... | £140 | ...\nHosting | ... | £35 | ...\nDomain | ... | £15 | ...\nLicence | ... | £40 | ...\nTOTAL: ...\nBUDGET: £2,500\nUNDER or OVER by: ...",
                   "Arithmetic must be consistent. Other costs are £90 if you keep all three fixed items.", 150),
                  ("short", "assume", "ASSUMPTIONS\nWrite two clear assumptions behind your numbers.",
                   "Assumption 1: ...\nAssumption 2: ...",
                   "Examples: licences already paid or not; whether reception training is in or out of these days.", 60),
                  ("short", "change", "CHANGE AND IMPACT\nWhat did you change from the over-budget draft?\nWhat is the risk of that change?",
                   "Change: ...\nImpact / risk: ...",
                   "Name a concrete cut or swap (days or a cost line) and what quality, scope or schedule risk it introduces.", 70)),
                E(9, "Compare two resource plans", "Both plans fit the budget. Choose with reasons and a risk.", WR, 8, ["Trade-offs"],
                  ("p", "plans", "Still Greenfield, budget £2,500. Fixed other costs £90 in both plans. Plan A: 9 developer days, 2 designer days, 1 tester day (more build, light testing). Plan B: 7 developer days, 2 designer days, 3 tester days (less build time, more dedicated testing). Both totals sit under £2,500."),
                  ("short", "pick", "Choose Plan A or Plan B for increment 1. Give two reasons for your choice. Name one disadvantage or risk of the plan you chose.",
                   "I choose Plan ... because (1) ... (2) ...\nDisadvantage / risk: ...",
                   "There is no single correct letter if your reasons link to quality, schedule or user risk. Do not invent FR/NFR lists from Week 4.", 90)),
            ],
        },
        {
            "title": "Lesson 3: Language and stack choice",
            "summary": "Compare realistic stacks using the taught criteria. Justify your recommendation. Do not choose only because it is a favourite.",
            "exercises": [
                E(1, "Choice depends on context", "There is no universal best language.", SC, 2, ["Language choice"],
                  ("single", "best", "Which statement is most accurate when choosing a language or stack for a client project?",
                   [("a", "There is one best language that every organisation should use"),
                    ("b", "The better choice depends on requirements, constraints and context for that project"),
                    ("c", "The newest language is always the safest choice for public services"),
                    ("d", "Only languages used in games count as professional for business systems")],
                   "b", "Suitability is judged against the project's needs and limits, not a global ranking.",
                   "Avoid treating any language as universally best.")),
                E(2, "Which points belong in the decision?", "Separate taught criteria from distractions.", CL, 4, ["Language choice"],
                  ("classify", "criteria", "For a language or stack decision, classify each point.",
                   [("criterion", "Taught decision criterion"), ("not", "Not a reliable criterion on its own")],
                   [("item-1", "How credentials and personal data will be protected", "criterion"),
                    ("item-2", "Whether the marketing logo uses a favourite colour", "not"),
                    ("item-3", "Existing staff skills and realistic training time", "criterion"),
                    ("item-4", "Licensing, hosting and ongoing cost", "criterion"),
                    ("item-5", "A viral social post claiming the language is 'finished'", "not")],
                   "Criteria include suitability, policy, security, staffing, cost, reliability, compatibility and maintainability.",
                   "Fashion and branding preferences are not enough on their own.")),
                E(3, "Match criteria to useful questions", "Each criterion should ask something concrete.", MA, 3, ["Language choice"],
                  ("match", "crit-q", "Match each criterion to a useful question for a gym membership booking app.",
                   [("sec", "Security"), ("cost", "Cost"), ("rel", "Reliability")],
                   [("q-sec", "How will member passwords and payment-related data be protected?"),
                    ("q-cost", "What licences, hosting and training will we pay for in year one?"),
                    ("q-rel", "What happens if the booking service fails on Monday evening peak?")],
                   {"sec": "q-sec", "cost": "q-cost", "rel": "q-rel"},
                   "Good criteria turn into questions the team can evidence.",
                   "Do not leave criteria as empty labels.")),
                E(4, "Skills matter, but they are not enough", "Spot the incomplete recommendation.", SC, 3, ["Staffing"],
                  ("single", "staff", "A teammate says: 'We should use Technology X because two of us already know it, so we will finish faster.' What is the strongest criticism of stopping there?",
                   [("a", "Staff skills never matter, so known tools should always be banned"),
                    ("b", "Speed from existing skills matters, but security, maintainability, compatibility, cost and reliability still need to be checked for this client"),
                    ("c", "Clients always forbid any technology staff already know"),
                    ("d", "Only brand-new languages are allowed on education projects")],
                   "b", "Known skills reduce training time, but they do not cancel other taught criteria.",
                   "Treat staffing as one factor alongside the other taught criteria.")),
                E(5, "Critique a weak recommendation", "Improve a realistic but incomplete argument.", WR, 8, ["Justification"],
                  ("p", "scenario", "Northline Leisure needs a browser-based class-booking system in about six weeks. A draft recommendation says: 'Use Technology X because two developers already know it and development should be quicker.'"),
                  ("short", "gaps", "Name three taught criteria this draft has failed to consider (not 'it should be cooler').",
                   "1. ...\n2. ...\n3. ...",
                   "Include criteria such as security, maintainability, compatibility, cost or reliability. Do not talk about logo taste.", 50),
                  ("short", "improve", "Rewrite the recommendation in four to six sentences so it still values existing skills but addresses the gaps you named.",
                   "Improved recommendation: ...",
                   "Keep Technology X only if you can defend it. Otherwise name a better-fit option and say why.", 100)),
                E(6, "Fit to an operating constraint", "Match the stack shape to how the system will be used.", SC, 3, ["Suitability"],
                  ("single", "travel", "Field staff need timetable views that still work when mobile signal drops. Which first-increment approach is best?",
                   [("a", "A depot-only desktop tool that requires a permanent high-speed link and cannot be used on the road"),
                    ("b", "A progressive web or mobile approach that caches timetable data and degrades usefully when offline"),
                    ("c", "A fully custom native app for one rare handset model the trust does not own, with no web fallback"),
                    ("d", "An always-online web page with no offline cache, on the assumption that rural signal never fails")],
                   "b", "Unreliable connectivity is the constraint. Caching and graceful offline behaviour match that need better than depot-only desktop, unsupported hardware, or always-online pages.",
                   "Match the approach to the operating constraint.")),
                E(7, "Plausible fit for a limited first increment", "Judge options against budget and existing tools, without straw men.", CL, 5, ["Compatibility"],
                  ("classify", "oak-fit", "Oakfield staff already use Microsoft 365 and have a limited budget for a first booking increment. Classify each option.",
                   [("suitable", "Worth serious evaluation now"), ("unsuitable", "Poor fit for increment 1")],
                   [("item-1", "A simple request form using existing Microsoft 365 tools the staff already have", "suitable"),
                    ("item-2", "Replacing Microsoft 365 entirely before any booking form is live", "unsuitable"),
                    ("item-3", "A small hosted web app with clear running costs the centre can afford", "suitable"),
                    ("item-4", "A custom runtime only one student on the course has ever used, with no handover notes", "unsuitable"),
                    ("item-5", "Keeping telephone booking while adding an online request route beside it", "suitable")],
                   "Suitable options respect budget, existing tools and continuity. Unsuitable options ignore staffing, cost or delivery risk for increment 1.",
                   "Familiar tools still need criteria. They are not automatic winners.")),
                E(8, "Compare three stacks for a booking system", "Score plausible options, then recommend with trade-offs.", WR, 18, ["Stack", "Justification"],
                  ("p", "scenario", "Brightside Community Trust needs a browser-based room-booking system for staff and tutors. Constraints: about six weeks to a first usable version; two developers who already know JavaScript well; limited budget; must store user account details; needs a database; must work on phones and shared PCs; another developer must be able to maintain it later; security and reliability matter."),
                  ("p", "options", "Option A: JavaScript (React) front end, Node.js API, PostgreSQL, small cloud host. Option B: Python (Django) with PostgreSQL on the same style of host (team would need focused Django training). Option C: Microsoft Power Platform or low-code on the Trust's existing Microsoft 365 tenant (faster start; licence limits and less custom logic)."),
                  ("short", "table", "Complete a brief comparison. Use short notes (not essays) in each cell.",
                   "Criteria | Option A (JS/Node) | Option B (Django) | Option C (Power Platform)\nSuitability | ... | ... | ...\nStaff skills | ... | ... | ...\nDevelopment time | ... | ... | ...\nCost | ... | ... | ...\nSecurity | ... | ... | ...\nReliability | ... | ... | ...\nCompatibility (phones/PCs) | ... | ... | ...\nMaintainability | ... | ... | ...",
                   "Every option should get an honest note. Do not leave a column empty.", 180),
                  ("short", "rec", "RECOMMENDATION\nWhich option do you choose for increment 1?",
                   "Recommendation: Option ...",
                   "Any of A, B or C can be defended if your reasons fit the constraints.", 20),
                  ("short", "reasons", "Give three reasons that use the criteria (not 'I like it').",
                   "Reason 1: ...\nReason 2: ...\nReason 3: ...",
                   "Tie each reason to a constraint or criterion above.", 70),
                  ("short", "trade", "TRADE-OFF\nWhat do you give up with your choice?",
                   "Trade-off: ...",
                   "Name a real weakness of the option you picked.", 40),
                  ("short", "reject", "OTHER OPTIONS\nWhy did you reject the other option(s)?",
                   "I rejected ... because...",
                   "Show you compared, not that the others are 'bad languages'.", 60)),
                E(9, "Final judgement under a new constraint", "Change one constraint and rethink.", SC, 3, ["Judgement"],
                  ("single", "shift", "Same Brightside booking system. Late news: the Trust's Microsoft 365 admin says Power Platform premium licences cannot be funded this year, but the two developers remain strong in JavaScript. Which recommendation is best for increment 1?",
                   [("a", "Force Option C anyway and hope licences appear during testing week"),
                    ("b", "Drop Option C for now and prefer a JavaScript-centred Option A (or a Django plan only if training time still fits), documenting the licence constraint"),
                    ("c", "Abandon browser support and build a kiosk-only system that ignores phones"),
                    ("d", "Choose a brand-new language neither developer has used so the team 'learns under pressure'")],
                   "b", "A hard licence block removes Option C for this increment. Existing JS skill and a documented constraint favour Option A unless training time for B is explicitly available.",
                   "Update the recommendation when a constraint changes. Do not ignore it.")),
            ],
        },
    ],
    "homework": {
        "title": "Homework: public project overruns",
        "summary": "Compare two public digital overruns and link them to schedule, cost, resource or assumption problems.",
        "id_suffix": "overruns",
        "minutes": 25,
        "topics": ["Planning", "Public projects"],
        "blocks": [
            ("h2", "Independent study"),
            ("p", "intro", "Find two well-known public digital projects that ran late, over budget, or both. Short, reliable notes are enough. Do not write a long essay."),
            ("short", "two", "For each project, name it and say whether the main issue looks most like schedule, cost, resources, or unrealistic assumptions (you may combine two). Add one sentence of evidence each.",
             "1. Project: ... Main issue: ... Evidence: ...\n2. Project: ... Main issue: ... Evidence: ...",
             "Use reputable news or official reports.", 80),
            ("short", "warn", "What warning does this give for a first software increment (Oakfield or another small service)? Link the warning to schedule, cost or resources.",
             "Warning: ... Because...",
             "Focus on planning discipline, not blaming a programming language.", 50),
        ],
    },
}
