"""Week 5 teaching blocks for the T Level OS curriculum generator.

Imported by generate-os-curriculum.py.

Week 5 taught lessons use one top-level activity per exercise
(approximately 9 per lesson). Count activities, not items on a
classification or drag-drop board.

LO1 / 1.1 — schedule tasks and milestones; allocate resources and estimate
costs; select a language using taught criteria.

Do not re-teach Week 3–4 content (FR/NFR, KPIs, acceptance, decomposition).
"""


def E(n, title, summary, kind, minutes, topics, *blocks):
    return {
        "id": f"ex-{n:02d}",
        "title": title,
        "summary": summary,
        "type": kind,
        "minutes": minutes,
        "topics": list(topics),
        "blocks": list(blocks),
    }


SC = "Single choice"
CL = "Classification"
MA = "Matching"
WR = "Written response"

WEEK_5 = {
    "n": 5,
    "title": "Scheduling, Resources, Cost and Language Choice",
    "wc": "2026-09-28",
    "phase": "analyse-problem",
    "practice": "LO1 / 1.1 — schedule tasks and milestones; allocate resources and estimate costs; select a language using taught criteria",
    "lo_ids": ["lo1"],
    "outcomes": [
        ("w5-schedule", "Schedule tasks, subtasks and milestones"),
        ("w5-resources-cost", "Allocate resources and estimate project costs"),
        ("w5-language", "Select a language using the taught criteria"),
    ],
    "lessons": [
        {
            "title": "Lesson 1: Milestone plan",
            "summary": "Distinguish tasks, subtasks and milestones; sequence work with dependencies, testing and client review.",
            "exercises": [
                E(1, "What is a milestone?", "A checkpoint of completed work, not a day-to-day task.", SC, 2, ["Milestones"],
                  ("single", "ms", "In a software project schedule, a milestone is best described as:",
                   [("a", "Any email sent during the project"), ("b", "A checkpoint that shows a meaningful piece of work is complete"), ("c", "The name of the programming language"), ("d", "A meeting with no agenda")],
                   "b", "Milestones mark completed progress you can check. They are not every small action.", "Look for a verifiable point of progress, not background chat.")),
                E(2, "Task or subtask?", "Subtasks break a larger task into smaller steps.", SC, 2, ["Tasks"],
                  ("single", "sub", "A college is building a room-booking web form. Which is most clearly a subtask of 'build the booking form'?",
                   [("a", "Open the service to the whole county"), ("b", "Wire the date picker and validate that the room is free"), ("c", "Write the final board report for governors"), ("d", "Choose a new college logo")],
                   "b", "Validating the form fields is work inside building the form. Board reports and logos are separate work.", "A subtask sits under a larger task, not beside the whole project.")),
                E(3, "Classify schedule items", "Sort tasks, subtasks and milestones.", CL, 3, ["Scheduling"],
                  ("classify", "sort-items", "Classify each item for a gym membership app project.",
                   [("task", "Task"), ("subtask", "Subtask"), ("milestone", "Milestone")],
                   [("item-1", "Design the membership join screen", "task"),
                    ("item-2", "Add validation so under-16s need a parent contact", "subtask"),
                    ("item-3", "First usable join-and-pay flow ready for staff trial", "milestone"),
                    ("item-4", "Write the payment confirmation email template", "subtask"),
                    ("item-5", "Complete end-to-end test of join, pay and confirmation", "milestone")],
                   "Tasks are chunks of work. Subtasks are steps inside a task. Milestones are checkable completion points.",
                   "Do not call every email a milestone.")),
                E(4, "Match schedule terms", "Link each term to what it means in planning.", MA, 3, ["Scheduling"],
                  ("match", "terms", "Match each scheduling term to its meaning.",
                   [("dep", "Dependency"), ("par", "Parallel work"), ("slip", "Slip")],
                   [("m-dep", "One piece of work cannot start until another finishes"), ("m-par", "Two pieces of work can progress at the same time"), ("m-slip", "A planned date is delayed")],
                   {"dep": "m-dep", "par": "m-par", "slip": "m-slip"},
                   "Dependencies force order. Parallel work saves calendar time when resources allow. Slip means the plan moved.",
                   "Do not treat every delay as a new task.")),
                E(5, "Spot the dependency", "Some work must wait for other work.", SC, 2, ["Dependencies"],
                  ("single", "dep", "For an event-booking system, which statement correctly describes a dependency?",
                   [("a", "Writing the FAQ page cannot begin until the payment provider integration returns a booking reference"), ("b", "Choosing a colour for the footer must wait until the domain name is renewed in five years"), ("c", "User research and writing the privacy notice must always be done by the same person on the same day"), ("d", "Testing is optional if the developer feels confident")],
                   "a", "The FAQ can describe the payment flow only after the integration behaviour is known. That is a real dependency.", "Ask what information or output one task needs from another.")),
                E(6, "Sequential or parallel?", "Judge what can safely overlap.", CL, 3, ["Parallel work"],
                  ("classify", "seq-par", "For a small online retailer checkout project, classify each pair of activities.",
                   [("sequential", "Must be sequential"), ("parallel", "Can run in parallel")],
                   [("item-1", "Define the basket fields, then build the basket API that uses those fields", "sequential"),
                    ("item-2", "Draft help-centre articles while developers build the basket screen", "parallel"),
                    ("item-3", "Complete payment sandbox tests before going live with real card charges", "sequential"),
                    ("item-4", "Photograph product images while the product list page layout is being coded", "parallel"),
                    ("item-5", "Agree the live go-live checklist, then switch on real card charges", "sequential")],
                   "Parallel means independent enough not to block each other. Live charges depend on a agreed checklist after tests.",
                   "If one output is an input to the other, keep them sequential.")),
                E(7, "Weak schedule for a room-booking pilot", "Find what the plan left out.", SC, 2, ["Milestones"],
                  ("single", "weak", "A college room-booking pilot plan lists only: design screens, build screens, launch to staff. What is the main weakness?",
                   [("a", "It uses British English"), ("b", "It omits testing and client/staff review before launch"), ("c", "It mentions screens at all"), ("d", "It is shorter than twenty pages")],
                   "b", "A usable plan must include checking the work and getting feedback before launch, not only construction.", "Ask where testing and review sit in the order.")),
                E(8, "Improve a streaming team's plan", "Add missing checkpoints and order.", WR, 4, ["Schedule"],
                  ("p", "scenario", "A streaming service team plans: build playlist screen → polish animation → public launch. No testing or product-owner review is listed."),
                  ("short", "improve", "Rewrite the plan as five ordered milestones. Include testing and a review checkpoint. Justify why one milestone must come before another.",
                   "1. ... 2. ... 3. ... 4. ... 5. ... Justification: A before B because...",
                   "Keep milestones checkable. Do not invent Week 4 requirements wording.", 80)),
                E(9, "Which milestone first for Oakfield?", "Apply judgement to a familiar context.", SC, 2, ["Milestones"],
                  ("single", "oak-order", "Oakfield wants tutors to trial a first usable digital register. Which milestone should come first?",
                   [("a", "Roll out to every venue with no trial"), ("b", "Complete a supervised tutor trial of the register flow and capture issues"), ("c", "Rewrite the college prospectus"), ("d", "Replace all classroom Wi-Fi before any screen is designed")],
                   "b", "A first usable version needs a supervised trial and feedback before wide roll-out. Prospectus work is unrelated.", "Prefer a checkable trial milestone over an all-or-nothing launch.")),
            ],
        },
        {
            "title": "Lesson 2: Resources and a costed outline",
            "summary": "Identify people, tools and services; estimate costs with clear assumptions and trade-offs.",
            "exercises": [
                E(1, "What counts as a project resource?", "Resources are what the project consumes or needs.", SC, 2, ["Resources"],
                  ("single", "res", "Which item is most clearly a project resource for building a community-centre booking site?",
                   [("a", "A developer’s time for four weeks"), ("b", "The colour of the centre’s front door"), ("c", "A rumour that bookings will rise"), ("d", "The postcode of a different town")],
                   "a", "People time is a core resource. Door colour and rumours are not what you allocate in a costed outline.", "Ask what the project uses up: people, tools, licences, devices, services.")),
                E(2, "Classify resource types", "People, hardware, software and services.", CL, 3, ["Resources"],
                  ("classify", "res-type", "Classify each resource for a transport-app pilot.",
                   [("people", "People"), ("hardware", "Hardware"), ("software", "Software / licences"), ("service", "External service")],
                   [("item-1", "Two part-time developers for six weeks", "people"),
                    ("item-2", "Three Android test phones", "hardware"),
                    ("item-3", "Map API usage fees", "service"),
                    ("item-4", "IDE and cloud hosting subscription", "software"),
                    ("item-5", "Accessibility tester for two days", "people")],
                   "People do the work. Hardware is physical kit. Software/licences are tools you run. Services are bought capability such as APIs.",
                   "Do not put every cost under 'software'.")),
                E(3, "One-off or recurring cost?", "Timing of spend matters in a proposal.", SC, 2, ["Cost"],
                  ("single", "timing", "A gym membership app will use a paid SMS reminder service charged monthly. That SMS fee is best described as:",
                   [("a", "A one-off set-up cost only"), ("b", "A recurring cost while the service is used"), ("c", "Not a cost because learners pay membership"), ("d", "A milestone")],
                   "b", "Monthly charges continue after launch. That is recurring, not a single purchase.", "Ask whether the spend stops after set-up or keeps repeating.")),
                E(4, "Match cost ideas to examples", "Connect cost types to concrete items.", MA, 3, ["Cost"],
                  ("match", "cost-ex", "Match each cost idea to the best example for an event-booking project.",
                   [("one", "One-off cost"), ("rec", "Recurring cost"), ("hidden", "Easy-to-miss cost")],
                   [("e-one", "Buying a domain name for the first year"), ("e-rec", "Monthly hosting while the site stays live"), ("e-hidden", "Staff time to train reception on the new process")],
                   {"one": "e-one", "rec": "e-rec", "hidden": "e-hidden"},
                   "Domain purchase is typically up-front. Hosting repeats. Training time is real even when nobody invoices it.",
                   "Hidden costs are still costs.")),
                E(5, "Missing cost in a retailer plan", "Find what the estimate forgot.", SC, 2, ["Cost"],
                  ("single", "missing", "A small online retailer’s estimate lists: developer days, hosting, and a payment provider fee. It says nothing else. What important cost is most clearly missing?",
                   [("a", "A celebrity endorsement"), ("b", "Time for testing and fixing defects before launch"), ("c", "The price of tea in the staff room"), ("d", "International shipping for a product they do not sell")],
                   "b", "Testing and defect fixing consume people time and often get left out of thin estimates.", "Look for work that must happen before customers pay.")),
                E(6, "Choose within a limited budget", "Trade features against cost.", SC, 2, ["Trade-offs"],
                  ("single", "budget", "A community centre has £2,000 for a first booking increment. Which option best fits a limited first increment?",
                   [("a", "Build a custom native app for six phone brands before any web form exists"), ("b", "Use existing Microsoft 365 tools for a simple request form and review process, then cost a later phase"), ("c", "Hire a full marketing agency and delay any booking work"), ("d", "Buy biometric turnstiles for every room")],
                   "b", "A first increment should stay inside budget and reuse existing tools where they already fit. Multi-platform apps and turnstiles blow a small budget.", "Prefer a scoped early increment over an all-features launch.")),
                E(7, "Strong or weak cost assumption?", "Assumptions must be stated and checkable.", CL, 3, ["Assumptions"],
                  ("classify", "assume", "Classify each statement for a college booking estimate.",
                   [("strong", "Useful stated assumption"), ("weak", "Weak / vague assumption")],
                   [("item-1", "We assume one developer at four days per week for three weeks", "strong"),
                    ("item-2", "We assume it will somehow be cheap", "weak"),
                    ("item-3", "We assume Microsoft 365 licences are already paid by the college", "strong"),
                    ("item-4", "We assume nobody will need training", "weak"),
                    ("item-5", "We assume accessibility testing needs two paid days", "strong")],
                   "Useful assumptions name roles, days, licences or test effort. Vague hope is not an assumption you can manage.",
                   "If the assumption is wrong, the plan should change.")),
                E(8, "Draft a simple costed outline", "People, other costs and assumptions.", WR, 4, ["Cost"],
                  ("p", "scenario", "A community organisation wants a first online room-request form. Budget is tight. Round numbers are fine."),
                  ("short", "cost", "Draft a simple costed outline for increment 1. List people time, other costs, and two assumptions.",
                   "People: ... Other: ... Assumptions: 1. ... 2. ...",
                   "Use days/roles, not fake precision. Include at least one non-people cost or training item.", 80)),
                E(9, "Explain a resource trade-off", "Say what you give up and why.", WR, 4, ["Trade-offs"],
                  ("short", "trade", "A gym app team can afford either a second developer for two weeks or paid accessibility testing — not both this month. Which would you choose for a first member-join increment, and what risk does the other choice leave?",
                   "I would choose... because... The risk of not choosing the other is...",
                   "There is no single right answer if your reasons are tied to users, schedule or quality.", 70)),
            ],
        },
        {
            "title": "Lesson 3: Language and stack choice",
            "summary": "Recommend a language or stack against suitability, policy, security, staffing, cost and reliability — not personal favourites alone.",
            "exercises": [
                E(1, "Is there one best language?", "Choice depends on context.", SC, 2, ["Language choice"],
                  ("single", "best", "Which statement is most accurate for choosing a programming language on a client project?",
                   [("a", "There is one best language for every organisation"), ("b", "The best choice depends on requirements, constraints and context"), ("c", "The newest language is always safest"), ("d", "Only languages used in gaming are professional")],
                   "b", "Suitability is judged against the project’s needs and limits, not a global ranking.", "Avoid treating any language as universally best.")),
                E(2, "Taught criteria or not?", "Separate decision criteria from distractions.", CL, 3, ["Language choice"],
                  ("classify", "criteria", "For a language/stack decision, classify each point.",
                   [("criterion", "Taught decision criterion"), ("not", "Not a reliable criterion")],
                   [("item-1", "Security and how credentials are handled", "criterion"),
                    ("item-2", "Whether the logo uses a favourite colour", "not"),
                    ("item-3", "Existing staff skills and training time", "criterion"),
                    ("item-4", "Licensing and ongoing cost", "criterion"),
                    ("item-5", "A social-media post saying the language is 'dead'", "not")],
                   "Criteria include suitability, policy, scalability, security, staffing, cost and reliability.",
                   "Fashion and branding preferences are not enough on their own.")),
                E(3, "Staffing is one factor, not the only one", "Balance skill with other criteria.", SC, 2, ["Staffing"],
                  ("single", "staff", "A teammate wants language X only because they already know it. Why is that incomplete as a recommendation?",
                   [("a", "Skills never matter on projects"), ("b", "Staffing matters, but policy, security, cost and reliability must also be weighed for the client"), ("c", "Clients always ban languages staff know"), ("d", "Only brand-new languages are allowed")],
                   "b", "Known skills reduce training cost, but they do not cancel security, policy or total cost.", "Record the trade-off; do not stop at personal familiarity.")),
                E(4, "Match criteria to questions", "Each criterion asks something concrete.", MA, 3, ["Language choice"],
                  ("match", "crit-q", "Match each criterion to a useful question for a gym membership app.",
                   [("sec", "Security"), ("cost", "Cost"), ("rel", "Reliability")],
                   [("q-sec", "How will member passwords and payment data be protected?"), ("q-cost", "What licences, hosting and training will we pay for in year one?"), ("q-rel", "What happens if the booking service is down on Monday evening peak?")],
                   {"sec": "q-sec", "cost": "q-cost", "rel": "q-rel"},
                   "Good criteria turn into questions the team can evidence.",
                   "Do not leave criteria as empty labels.")),
                E(5, "Weak stack choice for a tournament site", "Spot the unjustified choice.", SC, 2, ["Stack"],
                  ("single", "weak-stack", "A gaming tournament platform must take entries and show live brackets. Which recommendation is weakest?",
                   [("a", "A web stack the team can host and monitor, with clear backup for peak load"), ("b", "An experimental language nobody on the team has used, chosen because a blog called it 'cool'"), ("c", "A managed cloud service with documented support hours during events"), ("d", "A stack already used for similar ticketing/bracket tools, with a training plan")],
                   "b", "Novelty alone is a weak reason when reliability at peak entry time matters.", "Ask for evidence against the taught criteria.")),
                E(6, "Better fit for a travel app", "Apply criteria to a short scenario.", SC, 2, ["Suitability"],
                  ("single", "travel", "A transport app needs offline-tolerant timetable views for field staff with limited connectivity. Which choice is most defensible for a first increment?",
                   [("a", "A heavy desktop-only install that needs a permanent high-speed link"), ("b", "A progressive web or mobile approach that caches timetable data and degrades gracefully offline"), ("c", "A blockchain ledger for every bus stop visit"), ("d", "A print-only PDF with no digital update path")],
                   "b", "The constraint is unreliable connectivity. Caching and graceful offline behaviour match that need better than always-online desktop or unrelated tech.", "Match the stack to the operating constraint.")),
                E(7, "Suitable or unsuitable for Oakfield?", "Reuse a familiar constraint set lightly.", CL, 3, ["Compatibility"],
                  ("classify", "oak-fit", "Oakfield staff already use Microsoft 365 and have a limited budget. Classify each option for a first booking increment.",
                   [("suitable", "Worth serious evaluation now"), ("unsuitable", "Poor fit for increment 1")],
                   [("item-1", "A simple web form on existing Microsoft 365 tools", "suitable"),
                    ("item-2", "A full rewrite of Microsoft 365 itself", "unsuitable"),
                    ("item-3", "A small hosted web app the centre can afford to run", "suitable"),
                    ("item-4", "A bespoke language runtime that only one student knows", "unsuitable"),
                    ("item-5", "Keeping telephone booking while adding an online request route", "suitable")],
                   "Suitable options respect budget, existing tools and continuity. Unsuitable options ignore staffing and cost constraints.",
                   "Familiar tools can still be evaluated; they are not automatic winners without criteria.")),
                E(8, "Reject one option with reasons", "Show you can say no with criteria.", WR, 4, ["Justification"],
                  ("p", "scenario", "A streaming start-up wants a catalogue and watchlist. Someone proposes a rare experimental stack with no security track record and no staff experience."),
                  ("short", "reject", "Explain why you would not choose that stack for increment 1. Refer to at least two taught criteria.",
                   "I would not choose it because... Criteria: ...",
                   "Mention security/reliability and staffing or cost. Do not invent FR/NFR lists from Week 4.", 70)),
                E(9, "Justify a stack for a retailer", "Score against criteria, not preference.", WR, 4, ["Justification"],
                  ("short", "justify", "Recommend a language or stack for a small online retailer’s first checkout increment. Score it briefly against suitability, staffing, cost, security and reliability. Name one option you reject and why.",
                   "Recommendation: ... Suitability: ... Staffing: ... Cost: ... Security: ... Reliability: ... Reject: ... because...",
                   "Keep scores short. Show the trade-off; do not claim a universal best language.", 100)),
            ],
        },
    ],
    "homework": {
        "title": "Homework: public project overruns",
        "summary": "Compare two public digital overruns and link them to schedule, cost, resource or assumption problems.",
        "id_suffix": "overruns",
        "minutes": 25,
        "topics": ["Planning", "Public projects"],
        "blocks": [
            ("h2", "Independent study"),
            ("p", "intro", "Find two well-known public digital projects that ran late, over budget, or both. You only need short, reliable notes — not a long essay."),
            ("short", "two", "For each project, name it and say whether the main issue looks most like schedule, cost, resources, or unrealistic assumptions (you may combine two).",
             "1. Project: ... Main issue: ... 2. Project: ... Main issue: ...",
             "Use reputable news or official reports. One sentence of evidence per project is enough.", 50),
            ("short", "warn", "What warning does this give for a first software increment (Oakfield or another small service)? Link your warning to schedule, cost or resources.",
             "Warning: ... Because...",
             "Focus on planning discipline, not blaming a programming language.", 40),
        ],
    },
}
