"""Week 1 teaching blocks for the T Level OS curriculum generator.

Imported by generate-os-curriculum.py.

Week 1 taught lessons use one top-level activity per exercise. Count
activities, not items on a classification or drag-drop board.
"""


def E(n, title, summary, kind, minutes, topics, *blocks):
    return {
        "id": f"ex-{n:02d}",
        "title": title,
        "summary": summary,
        "type": kind,
        "minutes": minutes,
        "topics": list(topics),
        "blocks": list(blocks),
    }


SC = "Single choice"
CL = "Classification"
MA = "Matching"
WR = "Written response"

WEEK_1 = {
    "n": 1,
    "title": "Client Brief, Context and Initial Research",
    "wc": "2026-08-31",
    "phase": "analyse-problem",
    "practice": "LO1 / 1.1: interpret a client brief; research the market, problems and risks; investigate current hardware and software",
    "lo_ids": ["lo1"],
    "clientScenario": None,  # filled by the generator so the brief stays in one place
    "outcomes": [
        ("w1-interpret-brief", "Interpret a client request or project brief"),
        ("w1-research-market", "Research the market environment, common problems and risks"),
        ("w1-investigate-systems", "Investigate current hardware and software used in the context"),
    ],
    "lessons": [
        {
            "title": "Lesson 1: Annotating the client brief",
            "summary": "Use the Oakfield scenario to identify the client, users, current situation, problems, requirements and constraints.",
            "exercises": [
                E(1, "Who is the client?", "Pick the organisation that requested the work.", SC, 2, ["Client"],
                  ("single", "client", "Who is the client in the Oakfield scenario?",
                   [("a", "Adult learners who book a course"), ("b", "Oakfield Adult Skills Hub, the organisation requesting the system"), ("c", "Tutors who take a register"), ("d", "Microsoft, because staff already use 365")],
                   "b", "The client is the organisation that asked for the work. Oakfield Adult Skills Hub requested the service.", "Learners and tutors will use the service. They are users, not the organisation that requested it.")),
                E(2, "How do learners request a place?", "Use the current process in the brief.", SC, 2, ["Current situation"],
                  ("single", "now", "How do learners usually request a place today?",
                   [("a", "They book online and get an instant confirmation"), ("b", "They telephone or visit reception"), ("c", "They scan a QR code in the classroom"), ("d", "They email a central bookings team with a reference number")],
                   "b", "The brief says learners usually telephone or visit reception. Analyse that current practice, not a typical commercial booking site.", "Look at what the brief says happens now.")),
                E(3, "How is attendance recorded?", "Find the method tutors use in class.", SC, 2, ["Current situation"],
                  ("single", "attendance", "How do tutors record attendance during lessons today?",
                   [("a", "They mark a live dashboard on a tablet"), ("b", "They use paper registers"), ("c", "They scan learner ID badges"), ("d", "They wait for managers to complete a funding form")],
                   "b", "The brief says tutors use paper registers during lessons. That is the current attendance method.", "Do not assume a digital register already exists.")),
                E(4, "What do managers not know?", "Find the capacity gap in the brief.", SC, 2, ["Problems"],
                  ("single", "capacity", "What do managers often not know until the end of the week?",
                   [("a", "Which tutor prefers morning classes"), ("b", "Whether a course is full"), ("c", "Which programming language the new service will use"), ("d", "The name of the local authority")],
                   "b", "Managers have limited visibility of course capacity and often do not know if a course is full until information is updated at the end of the week.", "The gap is timely capacity information, not branding or technology choice.")),
                E(5, "Which statement is a constraint?", "A constraint limits the work.", SC, 2, ["Constraints"],
                  ("single", "constraint-stmt", "Which statement from the brief is a constraint?",
                   [("a", "Learners should be able to find available courses"), ("b", "Tutors should be able to record attendance"), ("c", "The project has a limited budget"), ("d", "Managers should be able to monitor attendance")],
                   "c", "A limited budget restricts what you can propose. The other options are things the service should allow people to do.", "A constraint limits the work. A requirement describes what the service should do.")),
                E(6, "Which statement is a problem?", "A problem is harm or extra work happening now.", SC, 2, ["Problems"],
                  ("single", "problem-stmt", "Which statement describes a current problem?",
                   [("a", "Staff already use Microsoft 365"), ("b", "Personal data must follow UK GDPR"), ("c", "Staff retype paper registers into a spreadsheet after the lesson"), ("d", "The service should support screen-reader users")],
                   "c", "Retyping the same attendance facts is extra work happening now. Microsoft 365 and UK GDPR are limits. Screen-reader support is a requirement.", "A problem is harm or inefficiency happening now, not a rule or a hoped-for feature.")),
                E(7, "Who would use the service?", "Sort each group as a user or not.", CL, 3, ["Users"],
                  ("classify", "users", "Sort each group. Who would use the proposed digital service?",
                   [("user", "User of the proposed system"), ("not-user", "Not a user of the proposed system")],
                   [("item-1", "Learners looking for a course", "user"),
                    ("item-2", "Tutors recording attendance", "user"),
                    ("item-3", "Managers checking whether a course is full", "user"),
                    ("item-4", "The T Level tutor teaching this unit", "not-user"),
                    ("item-5", "Microsoft support staff", "not-user")],
                   "Learners, tutors and managers are named as people who will use the service.",
                   "The client requested the work. That does not make every nearby organisation a user.")),
                E(8, "Client, user or neither", "Place each person or group.", CL, 3, ["Client", "Users"],
                  ("classify", "parties", "Is each person or group the client, a user, or neither?",
                   [("client", "Client"), ("user", "User"), ("neither", "Neither")],
                   [("item-1", "Oakfield Adult Skills Hub as the organisation requesting the work", "client"),
                    ("item-2", "An adult learner looking up an English course", "user"),
                    ("item-3", "A tutor completing a class register", "user"),
                    ("item-4", "A software vendor cold-calling Oakfield this week", "neither"),
                    ("item-5", "A manager producing a funding report", "user")],
                   "The client requested the service. Users are the people who will use it. A vendor offering a product is neither until Oakfield chooses them.",
                   "Do not treat every organisation that sells software as the client.")),
                E(9, "Current situation or problem", "Separate method-in-use from what is going wrong.", CL, 3, ["Current situation", "Problems"],
                  ("classify", "now-or-wrong", "Is each point how Oakfield works today, or something already going wrong?",
                   [("current", "Current situation"), ("problem", "Problem")],
                   [("item-1", "Learners telephone or visit reception to ask about courses", "current"),
                    ("item-2", "Staff retype paper information into a spreadsheet later", "problem"),
                    ("item-3", "Bookings are written in a paper diary", "current"),
                    ("item-4", "Staff at another venue cannot see the latest bookings straight away", "problem"),
                    ("item-5", "Tutors complete a paper register in the lesson", "current")],
                   "Current situation is the method in use. A problem is delay, duplication or missing information caused by that method.",
                   "Writing in a diary is current practice. Not being able to see that diary from another venue is the problem it creates.")),
                E(10, "Requirement or constraint", "Jobs the service should do versus limits on the work.", CL, 3, ["Requirements", "Constraints"],
                  ("classify", "req-or-limit", "Is each point something the service should do, or a limit on the work?",
                   [("requirement", "Requirement"), ("constraint", "Constraint")],
                   [("item-1", "Learners should be able to find available courses", "requirement"),
                    ("item-2", "Some teaching venues have unreliable Wi-Fi", "constraint"),
                    ("item-3", "Tutors should be able to record learner attendance", "requirement"),
                    ("item-4", "Staff would prefer to avoid unnecessary new systems or training", "constraint"),
                    ("item-5", "Managers should be able to view course capacity", "requirement")],
                   "Requirements are jobs the service should support. Constraints are conditions the design must live with.",
                   "Unreliable Wi-Fi and extra training are limits. Finding courses is a required job.")),
                E(11, "Classify mixed statements", "Current situation, problem, requirement or constraint.", CL, 4, ["Requirements"],
                  ("classify", "kinds", "Classify mixed statements from the Oakfield scenario.",
                   [("current", "Current situation"), ("problem", "Problem"), ("requirement", "Requirement"), ("constraint", "Constraint")],
                   [("item-1", "Staff record bookings in a paper diary and a shared spreadsheet", "current"),
                    ("item-2", "Managers often do not know whether a course is full until the end of the week", "problem"),
                    ("item-3", "Learners should be able to request a place on a course", "requirement"),
                    ("item-4", "Personal data must be handled in accordance with UK GDPR", "constraint"),
                    ("item-5", "Tutors use paper registers during lessons", "current"),
                    ("item-6", "The project has a limited budget", "constraint")],
                   "Current practice is what happens now. A problem is what goes wrong. A requirement is what the service should do. A constraint limits how you can do it.",
                   "A constraint such as UK GDPR is not a user task. A requirement is something the service should allow someone to do.")),
                E(12, "Stated, implied or unknown", "What the brief writes, what follows from it, and what you still need.", CL, 4, ["Requirements"],
                  ("classify", "stated", "Is each point stated in the brief, implied by it, or not yet known?",
                   [("stated", "Stated in the brief"), ("implied", "Implied by the brief"), ("unknown", "Not yet known")],
                   [("item-1", "Learners should be able to request a place", "stated"),
                    ("item-2", "Attendance recording should still work if venue Wi-Fi drops", "implied"),
                    ("item-3", "The exact project budget", "unknown"),
                    ("item-4", "The system must follow UK GDPR", "stated"),
                    ("item-5", "How many venues Oakfield uses", "unknown")],
                   "Stated points are written in the brief. Implied points follow from what is written, such as unreliable Wi-Fi affecting a live register. Unknowns need research.",
                   "Do not treat a missing figure as if the brief had already decided it.")),
                E(13, "Match stakeholder needs", "Drag each need to the stakeholder it mainly serves.", MA, 3, ["Users"],
                  ("match", "needs", "Match each need to the stakeholder it mainly serves.",
                   [("find", "Find courses and request a place"), ("register", "Record learner attendance"), ("reports", "Monitor capacity and produce funding reports")],
                   [("learner", "Learner"), ("tutor", "Tutor"), ("manager", "Manager")],
                   {"find": "learner", "register": "tutor", "reports": "manager"},
                   "The brief gives learners find-and-request, tutors attendance recording, and managers capacity and reports.",
                   "Match the need to the group who would do that job, not to whoever pays for the project.")),
                E(14, "Match tools to issues", "Drag each current tool to the issue it creates.", MA, 3, ["Current situation"],
                  ("match", "tool-issue", "Match each current tool to the issue it creates.",
                   [("diary", "Paper diary"), ("sheet", "Shared spreadsheet"), ("reg", "Paper registers")],
                   [("issue-diary", "Staff at another venue cannot see the latest bookings"), ("issue-sheet", "Learner details may be visible to people who do not need them"), ("issue-reg", "Attendance is typed again after the lesson")],
                   {"diary": "issue-diary", "sheet": "issue-sheet", "reg": "issue-reg"},
                   "Each current tool already creates a delay, a duplication or a data-access issue.",
                   "Think about who can see the information and when it is updated.")),
                E(15, "Match constraints to design", "Drag each constraint to the design concern it raises.", MA, 3, ["Constraints"],
                  ("match", "limit-design", "Match each constraint to the design concern it raises.",
                   [("budget", "Limited budget"), ("gdpr", "UK GDPR"), ("wifi", "Unreliable venue Wi-Fi"), ("m365", "Staff already use Microsoft 365")],
                   [("concern-budget", "A large custom build may be unrealistic"), ("concern-gdpr", "Who can see learner names and how that is logged"), ("concern-wifi", "A live-only register may fail in class"), ("concern-m365", "Extra logins and training if a separate system is added")],
                   {"budget": "concern-budget", "gdpr": "concern-gdpr", "wifi": "concern-wifi", "m365": "concern-m365"},
                   "A constraint is useful when it changes a design question, not when it is copied out as a slogan.",
                   "Budget affects scale. GDPR affects access. Wi-Fi affects offline working. Microsoft 365 affects training.")),
                E(16, "Match evidence to category", "Drag each note to stated, implied or unknown.", MA, 3, ["Requirements"],
                  ("match", "evidence-map", "Match each analyst note to the evidence category.",
                   [("stated-place", "Learners should be able to request a place"), ("implied-wifi", "Attendance recording should still work if venue Wi-Fi drops"), ("unknown-budget", "The exact project budget")],
                   [("cat-stated", "Stated in the brief"), ("cat-implied", "Implied by the brief"), ("cat-unknown", "Not yet known")],
                   {"stated-place": "cat-stated", "implied-wifi": "cat-implied", "unknown-budget": "cat-unknown"},
                   "Quote the brief for stated points. Draw a careful conclusion for implied points. Ask on site for unknowns.",
                   "Do not treat a missing figure as if the brief had already decided it.")),
                E(17, "Match requirements to stakeholders", "Drag each required job to who it mainly serves.", MA, 3, ["Requirements", "Users"],
                  ("match", "req-who", "Match each stated requirement to the stakeholder it mainly serves.",
                   [("req-find", "Find available courses and view useful information"), ("req-attend", "Record learner attendance"), ("req-fund", "Produce information required for funding reports")],
                   [("who-learner", "Learner"), ("who-tutor", "Tutor"), ("who-manager", "Manager")],
                   {"req-find": "who-learner", "req-attend": "who-tutor", "req-fund": "who-manager"},
                   "The brief lists learner, tutor and manager jobs separately. Match the job to the group who would do it.",
                   "The client requested the work. That does not mean every job is a manager job.")),
                E(18, "Match gaps to why they matter", "Drag each missing fact to why an analyst would ask for it.", MA, 3, ["Research questions"],
                  ("match", "missing-why", "Match each missing piece of information to why you would need it.",
                   [("gap-budget", "The exact project budget"), ("gap-venues", "How many venues Oakfield uses"), ("gap-editors", "Who can edit the shared spreadsheet")],
                   [("why-budget", "It affects how large the first version can be"), ("why-venues", "It affects hardware, Wi-Fi and rollout planning"), ("why-editors", "It affects who can see personal data")],
                   {"gap-budget": "why-budget", "gap-venues": "why-venues", "gap-editors": "why-editors"},
                   "Unknowns matter when they change cost, rollout or data access.",
                   "Do not invent a figure. Say why you would ask.")),
                E(19, "What should the analyst investigate next?", "Unreliable Wi-Fi should change the next question, not the colour scheme.", SC, 2, ["Research questions"],
                  ("single", "wifi", "Oakfield says some venues have unreliable Wi-Fi. What should the analyst investigate next?",
                   [("a", "Which colour scheme would look modern on a booking screen"), ("b", "Whether attendance still needs to be recorded when a venue is offline, and how staff do that today"), ("c", "Which programming language is most popular this year"), ("d", "Whether the Hub should move every course to a single city-centre building")],
                   "b", "Unreliable Wi-Fi affects a live digital register. Find out what happens in class today before you recommend a design.", "A Wi-Fi problem is about how the service must work in those venues, not about branding or the tech stack.")),
                E(20, "Explain client and user", "Name Oakfield and one user from the brief.", WR, 4, ["Client", "Users"],
                  ("short", "client-user", "Using Oakfield, explain the difference between the client and a user.", "The client is... A user is...", "Name Oakfield as the client and give one example user from the brief.", 50)),
                E(21, "Identify two problems", "Say what is going wrong and why it matters.", WR, 4, ["Problems"],
                  ("short", "two-problems", "Identify two problems with the current process and explain why each is a problem.", "1. ... because ... 2. ... because ...", "Pick delays, missing capacity information, duplicated typing or data sitting in a shared file.", 80)),
                E(22, "Identify implied requirements", "Start from Wi-Fi, accessibility, opening hours or Microsoft 365.", WR, 4, ["Requirements"],
                  ("short", "implied-two", "Identify two implied requirements and explain why they are implied rather than written as a list.", "1. ... It is implied because ... 2. ...", "Start from Wi-Fi, accessibility, opening hours or Microsoft 365.", 80)),
                E(23, "Justify a constraint", "Show how one limit should affect the first version.", WR, 4, ["Constraints"],
                  ("short", "constraints", "Choose one constraint from the brief and justify how it should affect the first version of the service.", "Constraint: ... It should affect the first version because...", "Use budget, UK GDPR, unreliable Wi-Fi or existing Microsoft 365. Do not just copy the constraint out.", 80)),
                E(24, "Use evidence from the brief", "Give one problem, one requirement, one constraint and one gap.", WR, 4, ["Requirements"],
                  ("short", "evidence", "From the brief, give one problem, one requirement, one constraint and one missing piece of information.", "Problem: ... Requirement: ... Constraint: ... Missing: ...", "Quote or closely paraphrase the scenario.", 80)),
                E(25, "Suggest follow-up questions", "Ask about numbers, venues, devices or what happens if Wi-Fi fails.", WR, 4, ["Research questions"],
                  ("short", "questions", "Write three questions an analyst should ask Oakfield before recommending a solution.", "1. ... 2. ... 3. ...", "Useful questions are specific: numbers, venues, devices, what happens if Wi-Fi fails.", 60)),
                E(26, "Why accessibility matters", "Use digital confidence, screen readers and English as an additional language.", WR, 4, ["Accessibility"],
                  ("short", "access-why", "Explain why accessibility matters in this Oakfield project.", "Accessibility matters because...", "Use the brief: different digital confidence, screen readers, and English as an additional language.", 80)),
                E(27, "Best follow-up question", "Choose the question that changes the design.", SC, 2, ["Research questions"],
                  ("single", "best-question", "Which follow-up question would help most before proposing a solution?",
                   [("a", "What colour should the home page use before we know who will use it?"), ("b", "Who is allowed to edit the shared spreadsheet, and how is that access reviewed?"), ("c", "Which stock photo of a classroom should appear on a poster?"), ("d", "Should the logo include a book or a laptop?")],
                   "b", "Spreadsheet access is about personal data and current practice. It changes the design. Branding guesses do not.", "Ask about who can see learner data, not about decoration.")),
                E(28, "Summarise the business problem", "Two or three sentences in your own words.", WR, 4, ["Problems"],
                  ("short", "summarise", "In your own words, summarise Oakfield's main business problem in two or three sentences.", "Oakfield's main problem is...", "Focus on delayed information, duplicated admin and learners who cannot easily request a place. Do not paste the brief.", 80)),
            ],
        },
        {
            "title": "Lesson 2: Market, problems and risks",
            "summary": "Look beyond the brief: market context, problems with the current approach, and risks if nothing changes.",
            "exercises": [
                E(1, "Which is the market point?", "A market point is about other providers or public expectation.", SC, 2, ["Market"],
                  ("single", "q1", "Which statement is about the wider market, not one user's need?",
                   [("a", "A learner uses a screen reader to look up courses"), ("b", "Other adult-learning providers already let people request a place online"), ("c", "A tutor wants a paper backup register"), ("d", "A manager wants Friday attendance figures")],
                   "b", "The market is other providers and what is already normal around Oakfield. One person's access need is still a user need.", "A user need belongs to a person using the service.")),
                E(2, "Why do other providers matter?", "Market research is about expectation, not copying a logo.", SC, 2, ["Market"],
                  ("single", "market-expect", "Why might other providers' online requests matter to Oakfield?",
                   [("a", "Because Oakfield must copy another organisation's brand colours"), ("b", "Because learners may already expect to request a place without visiting reception"), ("c", "Because Microsoft will refuse to work with any paper process"), ("d", "Because funding reports are only accepted from mobile apps")],
                   "b", "If similar services already take online requests, Oakfield's telephone-and-visit process may feel slow or closed to some learners.", "Market research is about expectation and alternatives, not copying a logo.")),
                E(3, "User need or market point", "Keep a person's job separate from what other providers offer.", CL, 3, ["Market", "User needs"],
                  ("classify", "need-or-market", "Is each statement a user need or a market point?",
                   [("need", "User need"), ("market", "Market / wider context")],
                   [("item-1", "A tutor needs attendance recorded before the class leaves", "need"),
                    ("item-2", "Many adult-learning providers now publish course lists online", "market"),
                    ("item-3", "A learner with low digital confidence still needs to request a place", "need"),
                    ("item-4", "Libraries and colleges nearby already offer online enrolment", "market"),
                    ("item-5", "A manager needs reliable capacity figures in the week, not after it", "need")],
                   "User needs describe a person trying to complete a job. Market points describe what similar services already do.",
                   "Keep Oakfield's tutor, learner and manager jobs separate from what other providers offer.")),
                E(4, "Problem now or future harm?", "If it is already wasting time, it is a problem.", SC, 2, ["Problems", "Risk"],
                  ("single", "problem-now", "Which point is a problem already happening, not a possible future harm?",
                   [("a", "A shared spreadsheet could be forwarded to the wrong person next term"), ("b", "Staff retype paper registers into a spreadsheet after the lesson"), ("c", "A future app store review might be poor"), ("d", "A new vendor might raise prices in three years")],
                   "b", "Retyping registers is work happening now. The other options are harms that might happen later.", "If it is already wasting time, it is a problem. If it might happen, it is a risk.")),
                E(5, "Constraint or risk?", "A constraint stays true even if nobody has been harmed yet.", SC, 2, ["Constraints", "Risk"],
                  ("single", "constraint-not-risk", "Which point is a constraint rather than a risk?",
                   [("a", "Learner names on a shared spreadsheet could be copied"), ("b", "Learners who will not use an app-only service may be unable to request a place"), ("c", "The project has a limited budget"), ("d", "Attendance updated too late could affect a funding report")],
                   "c", "A limited budget is a condition the work must live with. The others are harms that might follow from the current process or a poor design.", "A constraint stays true even if nobody has been harmed yet.")),
                E(6, "Classify Oakfield points", "Problem, risk or constraint.", CL, 3, ["Problems", "Risk"],
                  ("classify", "sort", "Classify each Oakfield point.",
                   [("problem", "Problem"), ("risk", "Risk"), ("constraint", "Constraint")],
                   [("item-1", "Managers often do not know if a course is full until the week has ended", "problem"),
                    ("item-2", "Personal data sitting in a shared spreadsheet could be copied or sent to the wrong person", "risk"),
                    ("item-3", "The project has a limited budget", "constraint"),
                    ("item-4", "Learners queuing at reception while staff search the diary", "problem")],
                   "A problem is already happening. A risk is harm that might happen. A constraint limits what you can propose.",
                   "Budget is a limit on the work, not a user complaint happening today.")),
                E(7, "Classify the current approach", "Problems now, risks if nothing changes, or constraints.", CL, 3, ["Problems", "Risk"],
                  ("classify", "kinds", "Classify each statement about Oakfield's current approach.",
                   [("problem", "Problem now"), ("risk", "Risk if nothing changes"), ("constraint", "Constraint")],
                   [("item-1", "Staff retype paper registers into a spreadsheet", "problem"),
                    ("item-2", "Learner data on a shared spreadsheet could be accessed by the wrong staff", "risk"),
                    ("item-3", "Some venues have unreliable Wi-Fi", "constraint"),
                    ("item-4", "Learners who will not use an app-only service may be unable to request a place", "risk"),
                    ("item-5", "Staff already use Microsoft 365 and extra systems mean extra training", "constraint")],
                   "Problems are happening now. Risks are harms that may follow. Constraints stay true even if you change the design.",
                   "Unreliable Wi-Fi limits the design. A data leak from a shared spreadsheet is a risk, not a budget limit.")),
                E(8, "Useful research for Oakfield", "Keep work that would change a recommendation.", CL, 3, ["Market research"],
                  ("classify", "useful", "Which investigation would help Oakfield, and which would not?",
                   [("useful", "Useful for Oakfield"), ("not-useful", "Not useful at this stage")],
                   [("item-1", "How other adult-learning providers take bookings", "useful"),
                    ("item-2", "Whether paper registers get lost or retyped", "useful"),
                    ("item-3", "Which colour palette looks fashionable this season", "not-useful"),
                    ("item-4", "What happens to attendance data if a venue is offline", "useful"),
                    ("item-5", "Which JavaScript framework is trending this month", "not-useful")],
                   "Useful research changes what you would recommend for Oakfield's users, data or venues.",
                   "Fashion and framework trends do not close a knowledge gap in this brief.")),
                E(9, "Sort planned research", "Skip work that would not change a requirement, risk or constraint.", CL, 3, ["Market research"],
                  ("classify", "useful-three", "Sort each planned research activity.",
                   [("useful", "Useful for Oakfield"), ("not-useful", "Not useful at this stage")],
                   [("item-1", "Ask tutors what they do if the register is still incomplete at the end of the session", "useful"),
                    ("item-2", "Compare two nearby adult-learning course pages for what they publish before a learner telephones", "useful"),
                    ("item-3", "Design a mascot before mapping how bookings are taken", "not-useful"),
                    ("item-4", "Check whether funding reports need attendance by a set weekday", "useful"),
                    ("item-5", "Survey staff about their favourite website animation", "not-useful")],
                   "Tutors, nearby providers and reporting deadlines affect the process. Mascots and animation do not.",
                   "If the answer would not change a requirement, a risk or a constraint, skip it for now.")),
                E(10, "Match findings to why they matter", "Stay with Oakfield's users, data and venues.", MA, 3, ["Market research"],
                  ("match", "matter-map", "Match each finding to why it matters for Oakfield.",
                   [("other", "Other adult-learning providers already take online requests"), ("sheet", "Learner names sit on a shared spreadsheet"), ("wifi", "Some venues have unreliable Wi-Fi")],
                   [("access", "Learners may expect to request a place without visiting reception"), ("gdpr", "Personal data could be copied or sent to the wrong person"), ("offline", "A live-only register may fail during a lesson")],
                   {"other": "access", "sheet": "gdpr", "wifi": "offline"},
                   "Each finding changes what you would investigate or recommend for Oakfield.",
                   "Stay with Oakfield's users, data and venues. Do not treat this as a generic booking app.")),
                E(11, "Match risks to impact", "Name who is harmed and how.", MA, 3, ["Risk"],
                  ("match", "risk-impact", "Match each risk to a likely impact.",
                   [("dup", "Diary and spreadsheet disagree"), ("late", "Attendance updated at the end of the week"), ("app", "Service offered only as a smartphone app")],
                   [("impact-dup", "A learner may be told a course is free when it is full"), ("impact-late", "Managers cannot produce timely funding information"), ("impact-app", "Learners with only a library PC may be unable to request a place")],
                   {"dup": "impact-dup", "late": "impact-late", "app": "impact-app"},
                   "A risk is useful when you can name who is harmed and how.",
                   "Think about learners, managers and people with limited devices, not about a generic outage.")),
                E(12, "Match market observations", "A trend only helps when it changes an Oakfield decision.", MA, 3, ["Market"],
                  ("match", "trend-oakfield", "Match each market observation to its relevance for Oakfield.",
                   [("online", "Course information is commonly published online before a person telephones"), ("phone", "Some public services still keep a telephone route"), ("train", "Staff training time is often underestimated in digital projects")],
                   [("rel-online", "Oakfield's reception-only route may feel slow next to nearby providers"), ("rel-phone", "Dropping the telephone route could exclude learners with low digital confidence"), ("rel-train", "A new system beside Microsoft 365 may fail if staff are not given time to learn it")],
                   {"online": "rel-online", "phone": "rel-phone", "train": "rel-train"},
                   "Market observations only help when they change an Oakfield decision.",
                   "Do not import a trend unless you can say who at Oakfield it affects.")),
                E(13, "Match sources to purpose", "Drag each research source to what it is for.", MA, 3, ["Market research"],
                  ("match", "source-purpose", "Match each research source to its purpose.",
                   [("src-nearby", "Two nearby adult-learning course pages"), ("src-tutor", "A short interview with a tutor after class"), ("src-report", "Last year's funding report deadline notes")],
                   [("pur-nearby", "See what learners can already do before they telephone"), ("pur-tutor", "Find out what happens if a register is still incomplete"), ("pur-report", "Check when attendance figures are needed")],
                   {"src-nearby": "pur-nearby", "src-tutor": "pur-tutor", "src-report": "pur-report"},
                   "Each source answers a different Oakfield question.",
                   "Do not treat every source as generic background reading.")),
                E(14, "Match issues to type", "Drag each issue to problem, risk or constraint.", MA, 3, ["Problems", "Risk"],
                  ("match", "issue-type", "Match each issue to whether it is a problem, a risk or a constraint.",
                   [("iss-retype", "Staff retype paper registers after the lesson"), ("iss-copy", "Learner names on a shared spreadsheet could be copied"), ("iss-budget", "The project has a limited budget")],
                   [("type-problem", "Problem now"), ("type-risk", "Risk if nothing changes"), ("type-constraint", "Constraint")],
                   {"iss-retype": "type-problem", "iss-copy": "type-risk", "iss-budget": "type-constraint"},
                   "A problem is already happening. A risk might happen. A constraint limits the design.",
                   "Budget is a limit on the work, not a complaint happening today.")),
                E(15, "Match problems to consequences", "Drag each current problem to a likely consequence.", MA, 3, ["Problems"],
                  ("match", "problem-conseq", "Match each current problem to a likely consequence.",
                   [("prob-queue", "Learners queue at reception while staff search the diary"), ("prob-late", "Capacity is updated at the end of the week"), ("prob-mismatch", "The diary and spreadsheet do not match")],
                   [("con-wait", "Some learners leave without requesting a place"), ("con-full", "Managers cannot see in time whether a course is full"), ("con-double", "A learner may be booked onto a course that is already full")],
                   {"prob-queue": "con-wait", "prob-late": "con-full", "prob-mismatch": "con-double"},
                   "A problem is useful when you can say what it causes for learners or staff.",
                   "Stay with Oakfield's bookings and capacity, not a generic outage.")),
                E(16, "Next research step", "Count and understand current use before changing a channel.", SC, 2, ["Market research"],
                  ("single", "next-research", "Oakfield wants to know whether to keep telephone booking. What is the best next research step?",
                   [("a", "Ask a web designer for three homepage layouts"), ("b", "Find out how many enquiries come by phone, and whether those learners also have internet access"), ("c", "Buy a new phone system before collecting any figures"), ("d", "Stop answering the phone for a week to test demand")],
                   "b", "You need volume and learner access before you drop or keep a channel. Layouts and shutting the phone line do not answer that.", "Count and understand current use before changing it.")),
                E(17, "Relevant data risk", "Name the people and the data.", SC, 2, ["Risk"],
                  ("single", "relevant-risk", "Which risk is most relevant if Oakfield puts learner names on a shared spreadsheet that many staff can open?",
                   [("a", "The spreadsheet font might look dated"), ("b", "Personal data could be seen, copied or sent to people who do not need it"), ("c", "A competitor might launch a similar spreadsheet"), ("d", "The file name might be hard to remember")],
                   "b", "Shared learner data is a UK GDPR issue. Appearance and file names are not the harm.", "Name the people and the data, not the decoration.")),
                E(18, "Useful market evidence", "Stay in adult learning and local alternatives.", SC, 2, ["Market"],
                  ("single", "market-evidence", "Which piece of market evidence is useful for Oakfield?",
                   [("a", "A social network changed its logo last month"), ("b", "Two nearby adult-learning providers let people request a place without visiting reception"), ("c", "A games company released a new handheld device"), ("d", "A lifestyle magazine ranked the 'best learning apps'")],
                   "b", "Nearby providers show what learners in the same area can already do. Logos, gadgets and magazine lists do not.", "Stay in adult learning and local alternatives.")),
                E(19, "Reduce duplicated admin", "Look at typing the same facts twice.", SC, 2, ["Problems"],
                  ("single", "admin-cut", "Staff currently retype paper registers into a spreadsheet. Which change would most clearly reduce that work?",
                   [("a", "Printing the register on thicker paper"), ("b", "Recording attendance once, in a system tutors and managers both use"), ("c", "Asking learners to shout their names twice"), ("d", "Changing the spreadsheet font to bold")],
                   "b", "The wasted work is typing the same facts twice. One shared attendance record removes the second typing, if it still works in class.", "Look at duplicated effort, not at how the paper looks.")),
                E(20, "Challenge an app-only jump", "Use constraints and users already in the scenario.", SC, 2, ["Risk"],
                  ("single", "challenge-risk", "A team wants to replace telephone booking with an app in one step. What is the strongest objection from the brief?",
                   [("a", "Apps cannot list course titles"), ("b", "Some learners have lower digital confidence, and some venues have unreliable Wi-Fi"), ("c", "Managers dislike all software"), ("d", "Paper diaries are required by UK law")],
                   "b", "The brief already names digital confidence and unreliable Wi-Fi. An app-only jump could shut people out or fail on site.", "Use constraints and users already in the scenario, not invented legal rules.")),
                E(21, "Explain problem, risk and constraint", "Give one Oakfield example of each.", WR, 4, ["Problems", "Risk"],
                  ("short", "prc-diff", "Explain the difference between a problem, a risk and a constraint. Give one Oakfield example of each.", "Problem: ... Risk: ... Constraint: ...", "A problem is happening now. A risk might happen. A constraint limits the design.", 100)),
                E(22, "Explain one risk's impact", "Say who is affected.", WR, 4, ["Risk"],
                  ("short", "risk-impact-write", "Choose one Oakfield risk and explain its possible impact.", "The risk is... The impact could be...", "Say who is affected: learners, tutors, managers or funders.", 80)),
                E(23, "Why a market finding matters", "Use nearby providers or a telephone route.", WR, 4, ["Market"],
                  ("short", "matter", "Choose one market finding that would be useful for Oakfield. Explain why it matters.", "Finding: ... It matters because...", "Use nearby providers, typical online requests, or whether similar services still keep a telephone route.", 80)),
                E(24, "Spreadsheet process problem", "Who can see the file, and when is it updated?", WR, 4, ["Problems"],
                  ("short", "sheet-problem", "Describe one problem caused by the shared spreadsheet process.", "The shared spreadsheet causes... because...", "Think about who can see the file, when it is updated, and whether it matches the paper diary.", 60)),
                E(25, "Reduce administrative work", "Stay with bookings, registers or capacity.", WR, 4, ["Problems"],
                  ("short", "admin-how", "Suggest one way a digital service could reduce administrative work at Oakfield, and explain how.", "A digital service could... It would reduce work by...", "Stay with bookings, registers or capacity, not with a generic app idea.", 80)),
                E(26, "Why research comes first", "Use Wi-Fi, Microsoft 365 and who cannot visit reception.", WR, 4, ["Market research"],
                  ("short", "research-first", "Explain why research should happen before proposing a solution.", "Research should come first because...", "Use Oakfield: Wi-Fi, Microsoft 365, who uses the spreadsheet, and who cannot visit reception.", 80)),
                E(27, "Why research a similar service", "Say what you would compare.", WR, 4, ["Market"],
                  ("short", "competitor", "Explain why a competitor or similar service might be worth researching.", "It is worth researching because...", "Say what you would compare: request a place, telephone option, or what is published before a visit.", 60)),
                E(28, "Personal data risk", "Use names on a shared spreadsheet and UK GDPR.", WR, 4, ["Risk"],
                  ("short", "data-risk", "Describe one risk linked to personal data in the current process and explain why it matters.", "The risk is... It matters because...", "Evidence from the brief: names on a shared spreadsheet, UK GDPR, who can open the file.", 80)),
            ],
        },
        {
            "title": "Lesson 3: Current systems and exit check",
            "summary": "Investigate current hardware, software and practice, then close the week with remaining unknowns.",
            "exercises": [
                E(1, "Which current practice is in the brief?", "Do not invent systems the brief never mentioned.", SC, 2, ["Current systems"],
                  ("single", "q1", "Which current practice is already in the brief?",
                   [("a", "A dedicated student records system with live dashboards"), ("b", "Telephone and reception enquiries, a paper diary, a shared spreadsheet and paper registers"), ("c", "An app store listing for Oakfield"), ("d", "Chip-and-PIN terminals in every classroom")],
                   "b", "The brief already names telephone, reception, diary, spreadsheet and paper registers.", "Do not invent systems the brief never mentioned.")),
                E(2, "Why mention Microsoft 365?", "The point is current software and training load.", SC, 2, ["Current systems"],
                  ("single", "which-m365", "Why does the brief mention Microsoft 365?",
                   [("a", "Because Oakfield wants to ban all Microsoft products"), ("b", "Because staff already use it and would prefer to avoid unnecessary new systems or training"), ("c", "Because UK GDPR only applies to Microsoft files"), ("d", "Because paper registers are stored inside Outlook")],
                   "b", "Staff already use Microsoft 365. Extra systems mean extra training. That is a constraint on the proposal.", "The point is current software and training load, not a legal slogan.")),
                E(3, "Telephone limitation", "Access depends on staff being free to answer.", SC, 2, ["Current systems"],
                  ("single", "phone-limit", "What limitation comes with telephone and reception enquiries?",
                   [("a", "Learners can only enquire when staff are free to answer"), ("b", "Telephone lines cannot carry a person's name"), ("c", "Reception desks are illegal under UK GDPR"), ("d", "Tutors must answer every call during a lesson")],
                   "a", "If staff are busy or the venue is closed, a learner cannot request a place. That is the limitation of the current channel.", "The brief does not ban reception. It does make access depend on staff being free.")),
                E(4, "Wi-Fi and a live register", "Do not assume perfect connectivity.", SC, 2, ["Current systems"],
                  ("single", "wifi-now", "Which current environment fact should shape a live digital register?",
                   [("a", "Every Oakfield venue has guaranteed fibre broadband"), ("b", "Some teaching venues have unreliable Wi-Fi"), ("c", "Tutors are forbidden from using paper"), ("d", "Registers are already taken automatically by cameras")],
                   "b", "Unreliable Wi-Fi is already in the brief. A design that only works while online may fail in class.", "Do not assume perfect connectivity or cameras.")),
                E(5, "Match tools to limitations", "Who can see the information, and when can a learner get an answer?", MA, 3, ["Current systems"],
                  ("match", "tools", "Match the current tool to a limitation.",
                   [("phone", "Telephone and reception"), ("diary", "Paper diary"), ("sheet", "Shared spreadsheet")],
                   [("lim-phone", "Learners can only enquire when staff are free to answer"), ("lim-diary", "Staff at another venue cannot see the latest bookings"), ("lim-sheet", "The wrong person may be able to open learner data")],
                   {"phone": "lim-phone", "diary": "lim-diary", "sheet": "lim-sheet"},
                   "Each current tool already creates a problem the new service has to deal with.",
                   "Think about who can see the information and when a learner can get an answer.")),
                E(6, "Match further tools", "Registers, existing software and connectivity all constrain a realistic design.", MA, 3, ["Current systems"],
                  ("match", "tools-more", "Match these further tools to a limitation.",
                   [("reg", "Paper registers"), ("office", "Microsoft 365"), ("wifi", "Venue Wi-Fi")],
                   [("lim-reg", "Attendance is typed again after the lesson"), ("lim-office", "Extra systems would mean extra training"), ("lim-wifi", "A cloud-only register may fail during the session")],
                   {"reg": "lim-reg", "office": "lim-office", "wifi": "lim-wifi"},
                   "Registers, existing software and connectivity all constrain a realistic design.",
                   "Think about duplicated typing, training load and what happens if a venue is offline.")),
                E(7, "Match facts to design questions", "Turn a current-system fact into a question you can take to Oakfield.", MA, 3, ["Current systems"],
                  ("match", "tools-four", "Match each environment fact to a design question.",
                   [("m365", "Staff already use Microsoft 365"), ("wifi2", "Some venues have unreliable Wi-Fi"), ("gdpr2", "Personal data must follow UK GDPR")],
                   [("q-m365", "Can the new service use existing logins instead of a separate account?"), ("q-wifi2", "How will tutors record attendance if the connection drops?"), ("q-gdpr2", "Who is allowed to see learner names, and is that access logged?")],
                   {"m365": "q-m365", "wifi2": "q-wifi2", "gdpr2": "q-gdpr2"},
                   "A current-system fact should turn into a question you can take to Oakfield.",
                   "Do not stop at copying the constraint. Ask how it would work on a Tuesday evening class.")),
                E(8, "Known or research gap", "If you cannot point to a sentence in the brief, treat it as a gap.", CL, 3, ["Current systems"],
                  ("classify", "gaps", "Is this already known from the brief, or still a research gap?",
                   [("known", "Known from the brief"), ("gap", "Still a research gap")],
                   [("item-1", "Staff already use Microsoft 365", "known"),
                    ("item-2", "Some venues have unreliable Wi-Fi", "known"),
                    ("item-3", "Exactly how many venues there are", "gap"),
                    ("item-4", "Bookings are recorded in a paper diary and a shared spreadsheet", "known"),
                    ("item-5", "Whether every classroom has a shared PC", "gap")],
                   "Known facts come from the brief. Gaps need a site visit, interview or sample of current files.",
                   "Microsoft 365 and Wi-Fi problems are already stated. Exact venue count is not.")),
                E(9, "More known or gap", "Channels, paper registers and budget are stated. Permissions and device lists are not.", CL, 3, ["Current systems"],
                  ("classify", "gaps-more", "Known from the brief, or still to check?",
                   [("known", "Known from the brief"), ("gap", "Still a research gap")],
                   [("item-1", "Tutors use paper registers during lessons", "known"),
                    ("item-2", "Who currently has permission to edit the shared spreadsheet", "gap"),
                    ("item-3", "Learners usually telephone or visit reception", "known"),
                    ("item-4", "Whether tutors have a work laptop in every venue", "gap"),
                    ("item-5", "The project has a limited budget", "known")],
                   "Channels, paper registers and budget are stated. Permissions and device lists are not.",
                   "If you cannot point to a sentence in the brief, treat it as a gap.")),
                E(10, "Useful investigation questions", "Uncover access, double-booking or offline working.", CL, 3, ["Research questions"],
                  ("classify", "ask", "Which questions would help an analyst investigate the current system?",
                   [("useful", "Useful question"), ("not-useful", "Not useful yet")],
                   [("item-1", "Who is allowed to edit the shared spreadsheet?", "useful"),
                    ("item-2", "What happens to a booking if two people telephone at once?", "useful"),
                    ("item-3", "Which stock photo of a handshake should appear on the home page?", "not-useful"),
                    ("item-4", "Can tutors take a register when the venue Wi-Fi is down?", "useful"),
                    ("item-5", "Which colour should the logo use before the process is mapped?", "not-useful")],
                   "Useful questions uncover access, double-booking, offline working or how Microsoft 365 is used now.",
                   "Branding guesses do not explain how the current system works.")),
                E(11, "Site-visit questions", "Ask about the job staff already do, not about decoration.", CL, 3, ["Research questions"],
                  ("classify", "ask-more", "Would this question help on a site visit?",
                   [("useful", "Useful question"), ("not-useful", "Not useful yet")],
                   [("item-1", "Which Microsoft 365 apps do staff already open for class lists?", "useful"),
                    ("item-2", "Is there a printer or shared PC in the classroom?", "useful"),
                    ("item-3", "Should the loading animation bounce or fade?", "not-useful"),
                    ("item-4", "How is a cancelled place removed from the diary and the spreadsheet?", "useful"),
                    ("item-5", "What is the project team's favourite website animation?", "not-useful")],
                   "Apps in use, classroom kit and cancellation steps change the design. Animation and films do not.",
                   "Ask about the job staff already do, not about decoration.")),
                E(12, "Sort planned questions", "If the answer would not change hardware, software or practice, leave it.", CL, 3, ["Research questions"],
                  ("classify", "ask-three", "Sort each planned question.",
                   [("useful", "Useful question"), ("not-useful", "Not useful yet")],
                   [("item-1", "How long does it take to type a register into the spreadsheet after class?", "useful"),
                    ("item-2", "Are there learners who only ever enquire by telephone?", "useful"),
                    ("item-3", "Should error messages use a serif font?", "not-useful"),
                    ("item-4", "Where is the paper diary stored overnight?", "useful"),
                    ("item-5", "Which stock photo of a classroom looks friendliest?", "not-useful")],
                   "Time, telephone-only learners and where the diary lives are current-system facts. Fonts and stock photos are not.",
                   "If the answer would not change hardware, software or practice, leave it.")),
                E(13, "Match tools to investigation questions", "Drag each current tool to the question it raises.", MA, 3, ["Current systems"],
                  ("match", "tool-ask", "Match each current tool to a useful investigation question.",
                   [("ask-phone", "Telephone and reception"), ("ask-sheet", "Shared spreadsheet"), ("ask-reg", "Paper registers")],
                   [("q-phone", "How many enquiries come when reception is closed?"), ("q-sheet", "Who currently has permission to edit the file?"), ("q-reg", "How long does retyping take after class?")],
                   {"ask-phone": "q-phone", "ask-sheet": "q-sheet", "ask-reg": "q-reg"},
                   "Each current tool should produce a question you can take on a visit.",
                   "Do not stop at naming the tool.")),
                E(14, "Match questions to research area", "Drag each question to hardware, software or practice.", MA, 3, ["Research questions"],
                  ("match", "q-area", "Match each investigation question to the area it belongs in.",
                   [("q-pc", "Is there a shared PC in the classroom?"), ("q-apps", "Which Microsoft 365 apps do staff open for class lists?"), ("q-cancel", "How is a cancelled place removed from the diary and the spreadsheet?")],
                   [("area-hw", "Hardware"), ("area-sw", "Software"), ("area-practice", "Current practice")],
                   {"q-pc": "area-hw", "q-apps": "area-sw", "q-cancel": "area-practice"},
                   "Hardware is kit. Software is what staff already log into. Practice is the steps they follow.",
                   "Keep the three areas separate so a visit has a clear purpose.")),
                E(15, "Match keep or replace", "Drag each current technology to a keep or replace reason.", MA, 3, ["Current systems"],
                  ("match", "keep-replace", "Match each current technology to a reason to keep or replace it in increment 1.",
                   [("kr-phone", "Telephone route"), ("kr-m365", "Microsoft 365"), ("kr-diary", "Paper diary as the only booking record")],
                   [("keep-phone", "Keep: some learners have lower digital confidence"), ("keep-m365", "Keep: staff already use it and extra training is a constraint"), ("replace-diary", "Replace as the only record: other venues cannot see the latest bookings")],
                   {"kr-phone": "keep-phone", "kr-m365": "keep-m365", "kr-diary": "replace-diary"},
                   "Keep what still serves a named user or constraint. Replace a record that already causes a named problem.",
                   "Use the brief. Do not replace everything in month one.")),
                E(16, "What to observe on a site visit", "Watch the job, not the furniture.", SC, 2, ["Research questions"],
                  ("single", "next-site", "You can visit one Oakfield venue this week. What should you observe first?",
                   [("a", "The colour of the corridor display boards"), ("b", "How a booking is taken, where it is written, and who can see that record afterwards"), ("c", "Whether the staff-room kettle is new"), ("d", "How the reception plants are arranged")],
                   "b", "You are investigating the current information process: capture, storage and access. Displays and plants do not explain that.", "Watch the job, not the furniture.")),
                E(17, "Why not replace everything", "Existing software, an analogue channel and weak connectivity are already in the brief.", SC, 2, ["Current systems"],
                  ("single", "replace-all", "A teammate says Oakfield should throw away Microsoft 365, paper and the phone line in month one. What is the strongest reason to slow down?",
                   [("a", "Paper can never store a person's name"), ("b", "Staff already use Microsoft 365, some learners use the telephone, and some venues have weak Wi-Fi"), ("c", "UK GDPR bans all digital systems"), ("d", "Tutors refuse to record attendance in any form")],
                   "b", "The brief already shows existing software, an analogue channel and weak connectivity. Replacing everything at once ignores those facts.", "The brief does not ban digital systems or attendance recording.")),
                E(18, "Compatibility before buying", "Compatibility here means existing accounts and files.", SC, 2, ["Current systems"],
                  ("single", "compat-next", "Which compatibility question should be investigated before buying a separate booking product?",
                   [("a", "Can staff sign in with the Microsoft 365 account they already use?"), ("b", "Does the product include a mascot builder?"), ("c", "Does the vendor brochure mention 'innovation'?"), ("d", "Does the demo video include background music?")],
                   "a", "Staff already use Microsoft 365. A second login and a second place to look up a class list is extra training and extra risk.", "Compatibility here means existing accounts and files, not marketing extras.")),
                E(19, "Unknown for a live register", "Ask about the workaround that already exists.", SC, 2, ["Unknowns"],
                  ("single", "challenge-unknown", "Which remaining unknown would most affect whether a live digital register is realistic?",
                   [("a", "The snacks available in the staff room"), ("b", "What tutors currently do if they cannot get a connection during the lesson"), ("c", "Whether the reception desk is oak or pine"), ("d", "The year the building was painted")],
                   "b", "If tutors already have an offline method, a live-only product may be rejected. Furniture and paint do not answer that.", "Ask about the workaround that already exists.")),
                E(20, "Why Microsoft 365 matters", "Think about training, login and extra systems.", WR, 4, ["Current systems"],
                  ("short", "compat", "Why does it matter that staff already use Microsoft 365?", "It matters because...", "Think about training, login and whether a new system would sit beside what they already open every day.", 80)),
                E(21, "One compatibility question", "Logins, class lists, or export to the spreadsheet they already use.", WR, 4, ["Current systems"],
                  ("short", "compat-q", "Describe one compatibility question that should be investigated at Oakfield.", "One question is...", "You might ask about logins, class lists, or whether a new tool can export to the spreadsheet they already use.", 60)),
                E(22, "Weak connectivity and design", "Talk about registers in class.", WR, 4, ["Current systems"],
                  ("short", "wifi-design", "Explain how weak connectivity could affect system design.", "Weak connectivity could affect the design because...", "Talk about registers in class, not about home broadband in general.", 80)),
                E(23, "Compare manual and digital", "What would improve, and what could get worse?", WR, 4, ["Current systems"],
                  ("short", "compare-manual", "Compare one manual Oakfield process with a possible digital alternative. What would improve, and what could get worse?", "Manual process: ... Digital alternative: ... Improve: ... Worse: ...", "Use bookings, registers or capacity. Mention Wi-Fi or training if relevant.", 100)),
                E(24, "Hardware, software and cost", "Extra licences, extra devices, or retraining.", WR, 4, ["Current systems"],
                  ("short", "cost-hw", "Explain how current hardware or software could affect cost.", "Cost could change because...", "Think about extra licences, extra devices, or retraining if staff already have Microsoft 365.", 80)),
                E(25, "Name an unknown", "Keep it specific: a venue, a file, a permission or a device.", WR, 4, ["Unknowns"],
                  ("short", "unknown", "Name one thing about Oakfield's current hardware, software or practice that the brief does not tell you. Why would you need it before proposing a solution?", "Unknown: ... Why I need it: ...", "Keep it specific: a venue, a file, a permission or a device.", 80)),
                E(26, "Recommend the next investigation", "Pick spreadsheet permissions, offline registers, venue kit, or telephone-only learners.", WR, 4, ["Research questions"],
                  ("short", "next-area", "Recommend one area Oakfield should investigate next and justify your choice.", "Investigate... because...", "Pick spreadsheet permissions, offline registers, venue kit, or telephone-only learners.", 80)),
                E(27, "What to keep in increment 1", "Telephone route, Microsoft 365, or a paper backup register.", WR, 4, ["Current systems"],
                  ("short", "replace-write", "Recommend one current Oakfield tool or channel that should stay in increment 1, and justify your choice.", "Keep: ... because...", "You might keep the telephone route, Microsoft 365, or a paper backup register. Use the brief.", 80)),
                E(28, "Known, gap or poor next step", "Do not spend the next visit on decoration.", CL, 3, ["Unknowns"],
                  ("classify", "last-sort", "Is each item known, a gap, or a poor next step?",
                   [("known", "Known from the brief"), ("gap", "Research gap"), ("poor", "Poor next step")],
                   [("item-1", "Tutors use paper registers", "known"),
                    ("item-2", "Whether a classroom PC is available in every venue", "gap"),
                    ("item-3", "Choosing homepage colours before mapping the current process", "poor"),
                    ("item-4", "Some venues have unreliable Wi-Fi", "known"),
                    ("item-5", "Who can edit the shared spreadsheet", "gap")],
                   "Paper registers and Wi-Fi are stated. Device lists and permissions are gaps. Homepage colours do not explain the current system.",
                   "Do not spend the next visit on decoration.")),
            ],
        },
    ],
    "homework": {
        "title": "Homework: one real digital product",
        "summary": "Analyse one real digital product or service using the same headings you used on the Oakfield brief.",
        "id_suffix": "product",
        "minutes": 25,
        "topics": ["Client", "Users", "Problem"],
        "blocks": [
            ("h2", "Independent study"),
            ("p", "intro", "Choose one real public or education service, such as booking, benefits, learning or libraries. Do not invent a fictional start-up. Short notes are enough."),
            ("short", "name", "Product or service name", "Name: ...", 8),
            ("short", "problem", "What problem does it address?", "Problem: ...", 30),
            ("short", "client", "Who is the likely client?", "Client: ...", 15),
            ("short", "users", "Who are the likely users?", "Users: ...", 15),
            ("short", "feature", "Name one useful feature.", "Feature: ...", 20),
            ("short", "limit", "Name one limitation or risk.", "Limitation or risk: ...", 30),
            ("short", "source", "What source did you use?", "Source: ...", "A public website, help page or app listing is enough.", 15),
        ],
    },
}
